//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Common {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Common.ApplicationResources", typeof(ApplicationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Credit.
        /// </summary>
        public static string AccountCredit {
            get {
                return ResourceManager.GetString("AccountCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a family member.
        /// </summary>
        public static string AddAFamilyMember {
            get {
                return ResourceManager.GetString("AddAFamilyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add it.
        /// </summary>
        public static string AddIt {
            get {
                return ResourceManager.GetString("AddIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new procedure or test.
        /// </summary>
        public static string AddProcedure {
            get {
                return ResourceManager.GetString("AddProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like this username already exists. Please login with your existing username and password. If you think we might have gotten confused, just send us an email to portal@compassphs.com..
        /// </summary>
        public static string AlreadyRegisteredMessage {
            get {
                return ResourceManager.GetString("AlreadyRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attestation.
        /// </summary>
        public static string Attestation {
            get {
                return ResourceManager.GetString("Attestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood pressure is the pressure of the blood in the circulatory system. It is measured as systolic over diastolic..
        /// </summary>
        public static string BloodPressureDefiniton {
            get {
                return ResourceManager.GetString("BloodPressureDefiniton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string CalendarTitle {
            get {
                return ResourceManager.GetString("CalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete.
        /// </summary>
        public static string CannotCompleteAction {
            get {
                return ResourceManager.GetString("CannotCompleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete task.
        /// </summary>
        public static string CannotCompleteTask {
            get {
                return ResourceManager.GetString("CannotCompleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Your Internet Connection..
        /// </summary>
        public static string CheckInternetConnection {
            get {
                return ResourceManager.GetString("CheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a reason.
        /// </summary>
        public static string ChooseAReason {
            get {
                return ResourceManager.GetString("ChooseAReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed - Nice Work!.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        public static string CompletedDate {
            get {
                return ResourceManager.GetString("CompletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you aren’t sure how to spell the name of your condition, try typing in the first few letters. We will provide hints as you type to help you out..
        /// </summary>
        public static string ConditionLookupErrorDetailMessage {
            get {
                return ResourceManager.GetString("ConditionLookupErrorDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn&apos;t find any results for.
        /// </summary>
        public static string ConditionLookupErrorMessage {
            get {
                return ResourceManager.GetString("ConditionLookupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Condition by name.
        /// </summary>
        public static string ConditionLookupPlaceholder {
            get {
                return ResourceManager.GetString("ConditionLookupPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats on completing this!.
        /// </summary>
        public static string CongratsOnCompleting {
            get {
                return ResourceManager.GetString("CongratsOnCompleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Completed.
        /// </summary>
        public static string DateCompleted {
            get {
                return ResourceManager.GetString("DateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are spelling your doctor&apos;s name correctly or that they are one of the following specialists (Internist, Family Practitioner)..
        /// </summary>
        public static string DoctorLookupErrorDetailMessage {
            get {
                return ResourceManager.GetString("DoctorLookupErrorDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn&apos;t find any results for.
        /// </summary>
        public static string DoctorLookupErrorMessage {
            get {
                return ResourceManager.GetString("DoctorLookupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Doctor&apos;s name.
        /// </summary>
        public static string DoctorLookupPlaceholder {
            get {
                return ResourceManager.GetString("DoctorLookupPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: get proper lingo from mktng.
        /// </summary>
        public static string DoctorLookupSearchErrorMessage {
            get {
                return ResourceManager.GetString("DoctorLookupSearchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Doctor&apos;s name.
        /// </summary>
        public static string DoctorPromptSearchPlaceholder {
            get {
                return ResourceManager.GetString("DoctorPromptSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosage.
        /// </summary>
        public static string Dosage {
            get {
                return ResourceManager.GetString("Dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to add your family member. Please try again..
        /// </summary>
        public static string ErrorAddingDependentMessage {
            get {
                return ResourceManager.GetString("ErrorAddingDependentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out every field in order to register..
        /// </summary>
        public static string FillOutAllFields {
            get {
                return ResourceManager.GetString("FillOutAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blood glucose test measures the amount of a type of sugar, called glucose, in your blood. Glucose comes from carbohydrate foods. It is the main source of energy used by the body..
        /// </summary>
        public static string GlucoseDefiniton {
            get {
                return ResourceManager.GetString("GlucoseDefiniton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian.
        /// </summary>
        public static string Guardian {
            get {
                return ResourceManager.GetString("Guardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDL cholesterol is the well-behaved &quot;good cholesterol.&quot; This friendly scavenger cruises the bloodstream. As it does, it removes harmful bad cholesterol from where it doesn&apos;t belong..
        /// </summary>
        public static string HdlCholesterolDefiniton {
            get {
                return ResourceManager.GetString("HdlCholesterolDefiniton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new diagnosis.
        /// </summary>
        public static string HealthDetailsConditionListAddButtonTitle {
            get {
                return ResourceManager.GetString("HealthDetailsConditionListAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will consider this information when making recommendations to you..
        /// </summary>
        public static string HealthDetailsConditionPromptBody {
            get {
                return ResourceManager.GetString("HealthDetailsConditionPromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Condition.
        /// </summary>
        public static string HealthDetailsConditionPromptButtonTitle {
            get {
                return ResourceManager.GetString("HealthDetailsConditionPromptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a condition we should know about?.
        /// </summary>
        public static string HealthDetailsConditionPromptHeader {
            get {
                return ResourceManager.GetString("HealthDetailsConditionPromptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking control of your health can be a bit daunting. Let us help you out by looking at your results below and identifying key areas of your health to tackle first..
        /// </summary>
        public static string HealthDetailsListHeader {
            get {
                return ResourceManager.GetString("HealthDetailsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgical procedure, mammogram, MRI, endoscopy, etc..
        /// </summary>
        public static string HealthDetailsProcedurePromptBody {
            get {
                return ResourceManager.GetString("HealthDetailsProcedurePromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an upcoming procedure.
        /// </summary>
        public static string HealthDetailsProcedurePromptButtonTitle {
            get {
                return ResourceManager.GetString("HealthDetailsProcedurePromptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information allows us to:
        ///• Identify risks before they become unmanagable
        ///• Provide a record of progress
        ///• Check off one of your incentives to save.
        /// </summary>
        public static string HealthDetailsProcedurePromptFooter {
            get {
                return ResourceManager.GetString("HealthDetailsProcedurePromptFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about any upcoming procedures or tests..
        /// </summary>
        public static string HealthDetailsProcedurePromptHeader {
            get {
                return ResourceManager.GetString("HealthDetailsProcedurePromptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can help you identify areas of concern..
        /// </summary>
        public static string HealthDetailsResultPromptBody {
            get {
                return ResourceManager.GetString("HealthDetailsResultPromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up a screening.
        /// </summary>
        public static string HealthDetailsResultPromptButtonTitle {
            get {
                return ResourceManager.GetString("HealthDetailsResultPromptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious about how to be a bit more proactive?.
        /// </summary>
        public static string HealthDetailsResultPromptHeader {
            get {
                return ResourceManager.GetString("HealthDetailsResultPromptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We know there can be a lot of reasons something can&apos;t happen be done right now. Let us know what&apos;s going on-and we hope you can come back later and have it done..
        /// </summary>
        public static string IncentiveActionCantCompleteDescription {
            get {
                return ResourceManager.GetString("IncentiveActionCantCompleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We were unable to get you the information you need for this action from the server. Please try again..
        /// </summary>
        public static string IncentiveActionDetailsDownloadError {
            get {
                return ResourceManager.GetString("IncentiveActionDetailsDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry you can&apos;t complete your %@ at this time..
        /// </summary>
        public static string IncentiveActionSorryCantComplete {
            get {
                return ResourceManager.GetString("IncentiveActionSorryCantComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By typing my full name, I am acknowledging and consenting to be held to these standards..
        /// </summary>
        public static string IncentiveAttestationDefaultDisclaimer {
            get {
                return ResourceManager.GetString("IncentiveAttestationDefaultDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass and your employer value your health and would like to encourage everyone to stay up to date with wellness exams and other important health activities. In some circumstances, you may request to be exempt from completing an activity. This submission will serve as a formal request to be exempt for the completion of a requirement. This exemption is applicable to the active period of your employer&apos;s existing incentive program. As such, this exemption is not indefinite and may require an update at a futur [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IncentiveCantCompleteAttestationText {
            get {
                return ResourceManager.GetString("IncentiveCantCompleteAttestationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We know there can be a lot of reasons something can’t be done right now. Let us know what’s going on—and we hope you can come back later and have it done..
        /// </summary>
        public static string IncentiveCantCompletePromptText {
            get {
                return ResourceManager.GetString("IncentiveCantCompletePromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your attestation. The purpose of this attestation is to indicate a valid medical reason for which you are prevented from completing an action that is part of your employer’s incentive program. Compass will process, retain, and protect this information subject to the Health Insurance Portability and Accountability Act (HIPAA). If you have questions about our full privacy protocols, our full privacy policy is available at http://www.compassphs.com/CompassUserTerms.pdf.
        /// </summary>
        public static string IncentiveCantCompleteTooltipText {
            get {
                return ResourceManager.GetString("IncentiveCantCompleteTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass and your employer value your health and would like to encourage everyone to stay up to date with wellness exams and other important health activities. In some circumstances, your procedures may not have been captured in the claims data received by Compass. This submission will serve as a self-attestation of the completion of a requirement. This attestation is applicable to the active period of your employer&apos;s existing incentive program. As such, this attestation is not indefinite and may require an  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IncentiveCompletedAttestionText {
            get {
                return ResourceManager.GetString("IncentiveCompletedAttestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentives you completed.
        /// </summary>
        public static string IncentiveSummaryCompletedTitle {
            get {
                return ResourceManager.GetString("IncentiveSummaryCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are good resources to be healthy-some of them earn rewards you can spend! We&apos;ll even tell you when it&apos;s getting time to do them :-).
        /// </summary>
        public static string IncentiveSummaryUncompletedSubtitle {
            get {
                return ResourceManager.GetString("IncentiveSummaryUncompletedSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentives you can earn.
        /// </summary>
        public static string IncentiveSummaryUncompletedTitle {
            get {
                return ResourceManager.GetString("IncentiveSummaryUncompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Need Help With....
        /// </summary>
        public static string INeedHelpWith {
            get {
                return ResourceManager.GetString("INeedHelpWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 4 of SSN.
        /// </summary>
        public static string LastFourSocial {
            get {
                return ResourceManager.GetString("LastFourSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 4 of Social Security Number.
        /// </summary>
        public static string LastFourSocialFull {
            get {
                return ResourceManager.GetString("LastFourSocialFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal First Name.
        /// </summary>
        public static string LegalFirstName {
            get {
                return ResourceManager.GetString("LegalFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get the verification details. What is the name of the doctor you saw?.
        /// </summary>
        public static string LetsGetVerificationDetails {
            get {
                return ResourceManager.GetString("LetsGetVerificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get the verification details. What is the procedure and the name of the doctor you saw?.
        /// </summary>
        public static string LetsGetVerificationDetailsWithProcedure {
            get {
                return ResourceManager.GetString("LetsGetVerificationDetailsWithProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, this is awkward! We had a little trouble processing your login, could you try once more for us?.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like your username or password doesn’t match our records. Give it another shot, or select ‘Forgot Password’ to reset. Head’s Up: To protect your information, we will lock your account after 5 failed login attempts..
        /// </summary>
        public static string LoginInvalidMessage {
            get {
                return ResourceManager.GetString("LoginInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh! It looks like you reached the maximum number of login attempts. To protect your account, you are unable to login at this time. Please email us at portal@compassphs.com or call 800.513.1667 x631 for assistance.
        /// </summary>
        public static string LoginLockedMessage {
            get {
                return ResourceManager.GetString("LoginLockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Logout?.
        /// </summary>
        public static string LogoutPromptBody {
            get {
                return ResourceManager.GetString("LogoutPromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout?.
        /// </summary>
        public static string LogoutPromptTitle {
            get {
                return ResourceManager.GetString("LogoutPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to save your selection. Please try again..
        /// </summary>
        public static string LookupAddingEntityErrorMessage {
            get {
                return ResourceManager.GetString("LookupAddingEntityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to save your medication. Please try again..
        /// </summary>
        public static string LookupAddingMedicationErrorMessage {
            get {
                return ResourceManager.GetString("LookupAddingMedicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to edit your selection. Please try again..
        /// </summary>
        public static string LookupEditingEntityErrorMessage {
            get {
                return ResourceManager.GetString("LookupEditingEntityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to delete your selection. Please try again..
        /// </summary>
        public static string LookupRemovingEntityErrorMessage {
            get {
                return ResourceManager.GetString("LookupRemovingEntityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to retrieve your list of dependents..
        /// </summary>
        public static string LookupRetrievingDependentsErrorMessage {
            get {
                return ResourceManager.GetString("LookupRetrievingDependentsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: get proper lingo from mktng.
        /// </summary>
        public static string LookupRetrievingPatientPrescriptionsErrorMessage {
            get {
                return ResourceManager.GetString("LookupRetrievingPatientPrescriptionsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: get proper lingo from mktng.
        /// </summary>
        public static string LookupRetrievingPatientProceduresErrorMessage {
            get {
                return ResourceManager.GetString("LookupRetrievingPatientProceduresErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO: get proper lingo from mktng.
        /// </summary>
        public static string LookupRetrievingPatientProvidersErrorMessage {
            get {
                return ResourceManager.GetString("LookupRetrievingPatientProvidersErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as completed.
        /// </summary>
        public static string MarkActionAsCompleted {
            get {
                return ResourceManager.GetString("MarkActionAsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical POA.
        /// </summary>
        public static string MedicalPOA {
            get {
                return ResourceManager.GetString("MedicalPOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh! It looks like the personal information you’ve provided doesn’t match our records. Not to worry, just email us at portal@compassphs.com and we will get you taken care of..
        /// </summary>
        public static string MemberNotFoundMessage {
            get {
                return ResourceManager.GetString("MemberNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Biometric Results.
        /// </summary>
        public static string MyBiometricResults {
            get {
                return ResourceManager.GetString("MyBiometricResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text here about risk factor counts and how to interpret the results below..
        /// </summary>
        public static string MyBiometricResultsDescription {
            get {
                return ResourceManager.GetString("MyBiometricResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no biometric results to view. This could be either because you have not been screened yet or because we are still processing your screening results..
        /// </summary>
        public static string MyBiometricResultsEmptyMessage {
            get {
                return ResourceManager.GetString("MyBiometricResultsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Doctor&apos;s name is....
        /// </summary>
        public static string MyDoctorsNameIs {
            get {
                return ResourceManager.GetString("MyDoctorsNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Full Name.
        /// </summary>
        public static string MyFullName {
            get {
                return ResourceManager.GetString("MyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Health Details.
        /// </summary>
        public static string MyHealthDetails {
            get {
                return ResourceManager.GetString("MyHealthDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Incentives.
        /// </summary>
        public static string MyIncentives {
            get {
                return ResourceManager.GetString("MyIncentives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cards Found.
        /// </summary>
        public static string NoCardsFound {
            get {
                return ResourceManager.GetString("NoCardsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone’s eager! The portal excites us, too. It looks like your Compass membership hasn’t started yet, or we are unable to match your information to an account in our system. Not to worry, your Health Pro consultant will email you as soon are you are eligible to log in. If you think this is an error, just send a message to portal@compassphs.com..
        /// </summary>
        public static string NotActiveMessage {
            get {
                return ResourceManager.GetString("NotActiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We type fast when we get excited, too. It looks like your passwords don’t match. Please click ‘OK’ to enter identical passwords..
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet.
        /// </summary>
        public static string Pet {
            get {
                return ResourceManager.GetString("Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        public static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We type fast when we get excited, too. It looks like your PINs don’t match. Please click ‘OK’ to enter an identical PIN..
        /// </summary>
        public static string PincodesDontMatch {
            get {
                return ResourceManager.GetString("PincodesDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone’s eager! The portal excites us, too. It looks like you reached the maximum number of login attempts with your PIN code. To protect your privacy, we’re going to send you back to the login page where you can enter your full password and create a new 4 digit PIN..
        /// </summary>
        public static string PINLockedOutMessage {
            get {
                return ResourceManager.GetString("PINLockedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN Not Valid.
        /// </summary>
        public static string PINNotValid {
            get {
                return ResourceManager.GetString("PINNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We type fast when we get excited, too. It looks like your PIN doesn’t match what we have saved for you. Please click ‘OK’ to retry..
        /// </summary>
        public static string PINWrongMessage {
            get {
                return ResourceManager.GetString("PINWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred First Name.
        /// </summary>
        public static string PreferredFirstName {
            get {
                return ResourceManager.GetString("PreferredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Differential.
        /// </summary>
        public static string PremiumDifferential {
            get {
                return ResourceManager.GetString("PremiumDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you aren’t sure how to spell the name of your medication, try typing in the first few letters. We will provide hints as you type to help you out..
        /// </summary>
        public static string PrescriptionLookupErrorDetailMessage {
            get {
                return ResourceManager.GetString("PrescriptionLookupErrorDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn&apos;t find any results for.
        /// </summary>
        public static string PrescriptionLookupErrorMessage {
            get {
                return ResourceManager.GetString("PrescriptionLookupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search prescription&apos;s name.
        /// </summary>
        public static string PrescriptionLookupPlaceholder {
            get {
                return ResourceManager.GetString("PrescriptionLookupPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a medication.
        /// </summary>
        public static string PrescriptionPromptButtonTitle {
            get {
                return ResourceManager.GetString("PrescriptionPromptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information allows us to:
        ///• Keep an up-to-date record of your medications
        ///• Provide alternative cheaper medication options
        ///• Send your Prescription information to your doctor.
        /// </summary>
        public static string PrescriptionPromptFooterText {
            get {
                return ResourceManager.GetString("PrescriptionPromptFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another prescription.
        /// </summary>
        public static string PrescriptionPromptListAddButtonTitle {
            get {
                return ResourceManager.GetString("PrescriptionPromptListAddButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking control of what you spend on Prescriptions can be difficult. Let us help you out by telling us what you are currently taking..
        /// </summary>
        public static string PrescriptionPromptListHeader {
            get {
                return ResourceManager.GetString("PrescriptionPromptListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Medications.
        /// </summary>
        public static string PrescriptionPromptPageTitle {
            get {
                return ResourceManager.GetString("PrescriptionPromptPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. Ezetimbe (Zetia).
        /// </summary>
        public static string PrescriptionPromptPlaceholder {
            get {
                return ResourceManager.GetString("PrescriptionPromptPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you currently taking any Medications?.
        /// </summary>
        public static string PrescriptionPromptTile {
            get {
                return ResourceManager.GetString("PrescriptionPromptTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not added any medications yet..
        /// </summary>
        public static string PrescriptionsPromptNotAdded {
            get {
                return ResourceManager.GetString("PrescriptionsPromptNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Date.
        /// </summary>
        public static string ProcedureDate {
            get {
                return ResourceManager.GetString("ProcedureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCEDURE HISTORY.
        /// </summary>
        public static string ProcedureHistory {
            get {
                return ResourceManager.GetString("ProcedureHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you aren’t sure how to spell the name of your procedure, try typing in the first few letters. We will provide hints as you type to help you out..
        /// </summary>
        public static string ProcedureLookupErrorDetailMessage {
            get {
                return ResourceManager.GetString("ProcedureLookupErrorDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We didn&apos;t find any results for.
        /// </summary>
        public static string ProcedureLookupErrorMessage {
            get {
                return ResourceManager.GetString("ProcedureLookupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. Colonoscopy.
        /// </summary>
        public static string ProcedureLookupPlaceholder {
            get {
                return ResourceManager.GetString("ProcedureLookupPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name.
        /// </summary>
        public static string ProcedureName {
            get {
                return ResourceManager.GetString("ProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated date.
        /// </summary>
        public static string ProcedurePromptDatePlaceholder {
            get {
                return ResourceManager.GetString("ProcedurePromptDatePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex. Colonoscopy.
        /// </summary>
        public static string ProcedurePromptPlaceholder {
            get {
                return ResourceManager.GetString("ProcedurePromptPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and sign below.
        /// </summary>
        public static string ReadAndSignBelow {
            get {
                return ResourceManager.GetString("ReadAndSignBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being healthy is worth more than money. Here&apos;s some things everyone should do for their own sake..
        /// </summary>
        public static string RecommendationSummarySubtitle {
            get {
                return ResourceManager.GetString("RecommendationSummarySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended actions.
        /// </summary>
        public static string RecommendationSummaryTitle {
            get {
                return ResourceManager.GetString("RecommendationSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, this is awkward! We had a little trouble processing your registration, could you try once more for us?.
        /// </summary>
        public static string RegistrationErrorMessage {
            get {
                return ResourceManager.GetString("RegistrationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to undo any changes..
        /// </summary>
        public static string RemoveAlertMessage {
            get {
                return ResourceManager.GetString("RemoveAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string RemoveAlertTitle {
            get {
                return ResourceManager.GetString("RemoveAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save it.
        /// </summary>
        public static string SaveIt {
            get {
                return ResourceManager.GetString("SaveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use your birthdate information to validate with your employer or spouses employer that you are registered for the service. This information is also used to make relevant recommendations and provide you with a better more personalized experience..
        /// </summary>
        public static string TooltipBirthdayMessage {
            get {
                return ResourceManager.GetString("TooltipBirthdayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need you to create a password that you can use to reset information on the app. This password can also be used to access your information via our online at member.compassphs.com..
        /// </summary>
        public static string TooltipCreateAPasswordMessage {
            get {
                return ResourceManager.GetString("TooltipCreateAPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use your Last 4 of your SSN to validate with your employer or spouses employer that you are registered for the service. This information is also used for confirmation security purposes. We will be providing you with confidential and personal medical information and want to do everything possible to ensure your information is safe and secure..
        /// </summary>
        public static string TooltipLastFourSsnMessage {
            get {
                return ResourceManager.GetString("TooltipLastFourSsnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need you to enter your password to login to the app and access protected healthcare data..
        /// </summary>
        public static string TooltipLoginPasswordMessage {
            get {
                return ResourceManager.GetString("TooltipLoginPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would like to know what first name you prefer, in the event that we need to provide you more specific information. Our Health Pros want to ensure that we are advocating for you in a way that is personal and attempt to do what is possible to make your experience with us most comfortable..
        /// </summary>
        public static string TooltipPreferredFirstNameMessage {
            get {
                return ResourceManager.GetString("TooltipPreferredFirstNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transgender.
        /// </summary>
        public static string Transgender {
            get {
                return ResourceManager.GetString("Transgender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triglycerides are a type of fat (lipid) found in your blood. When you eat, your body converts any calories it doesn&apos;t need to use right away into triglycerides..
        /// </summary>
        public static string TriglyceridesDefiniton {
            get {
                return ResourceManager.GetString("TriglyceridesDefiniton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again Later.
        /// </summary>
        public static string TryAgainLater {
            get {
                return ResourceManager.GetString("TryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY UPCOMING PROCEDURES &amp; TESTS.
        /// </summary>
        public static string UpcomingProcedures {
            get {
                return ResourceManager.GetString("UpcomingProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (email).
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my incentives.
        /// </summary>
        public static string ViewMyIncentives {
            get {
                return ResourceManager.GetString("ViewMyIncentives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your waist size is a clue to whether you&apos;re at high risk for type 2 diabetes, high blood pressure, high cholesterol, and heart disease..
        /// </summary>
        public static string WaistCirumferenceDefinition {
            get {
                return ResourceManager.GetString("WaistCirumferenceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your doctor&apos;s name?.
        /// </summary>
        public static string WhatIsYourDoctorsName {
            get {
                return ResourceManager.GetString("WhatIsYourDoctorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did you complete the procedure?.
        /// </summary>
        public static string WhenDidYouCompleteTheProcedure {
            get {
                return ResourceManager.GetString("WhenDidYouCompleteTheProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
