// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;

namespace iOS.Phone
{
	public partial class BiometricResultCell : UITableViewCell
	{
		public static readonly string Key = "BiometricResultCell";

		private BiometricResultStatus _status;
		public Action OnTouchUpInside { get; set; }

		public string Title { 
			get 
			{
				return TitleLabel.Text;
			}  
			set
			{
				TitleLabel.Text = value;
			}
		}

		public string Subtitle { 
			get 
			{
				return SubtitleLabel.Text;
			}  
			set
			{
				SubtitleLabel.Text = value;
			}
		}

		public string MeasurementValue { 
			get 
			{
				return MeasurementValueLabel.Text;
			}  
			set
			{
				MeasurementValueLabel.Text = value;
			}
		}

		public string MeasurementDate { 
			get 
			{
				return MeasurementDateLabel.Text;
			}  
			set
			{
				MeasurementDateLabel.Text = value;
			}
		}

		public BiometricResultStatus Status{
			get{
				return _status;
			}

			set
			{
				_status = value;
				if (value == BiometricResultStatus.InRange) {
					StatusImageView.Image = UIImage.FromFile ("GreenCheckBox.png");
					SubtitleLabel.TextColor = SharedColors.LightGray.ToUIColor();
				} else {
					StatusImageView.Image = UIImage.FromFile ("OrangeWarningTriangle.png");
					SubtitleLabel.TextColor = SharedColors.Orange.ToUIColor();
				}
			}
		}

		public void HideDrilldownButton()
		{
			DrillDownButton.Hidden = true;
		}

		public void ShowDrilldownButton()
		{
			DrillDownButton.Hidden = false;
		}

		public BiometricResultCell (IntPtr handle) : base (handle)
		{

		}
	}
}
