// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.VM;
using PDRatingSample;
using GalaSoft.MvvmLight.Helpers;
using CoreGraphics;

namespace iOS.Phone
{
	public partial class DrRecCell : BaseRecommendationCell
	{
		public static string Key = new NSString("DrRecCell");

		public DrRecCell (IntPtr handle) : base (handle) { }

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			this.ActionButton.TouchUpInside += OnTouchUpInside;
		}

		public override nfloat CalculateHeight (BaseRecommendationListItemViewModel viewModel)
		{
			nfloat height = UITableView.AutomaticDimension;

			if(Device.OS < 8)
			{
				Configure (viewModel, null);

				height = this.ContentView.SystemLayoutSizeFittingSize (UILayoutFittingCompressedSize).Height;
				height += SuperlativeLabel.HeightToFitContent ();	
			}

			return height;
		}

		public override void Configure (BaseRecommendationListItemViewModel baseVM, Action<object, EventArgs> touchUpAction)
		{
			var viewModel = (DoctorRecommendationListItemViewModel)baseVM;
			this.StarView.AddStarRatingControl (viewModel.Rating);

			// Bind the remaining elements
			this.NameLabel.Text = viewModel.Title;
			this.SpecialtyLabel.Text = viewModel.SubTitle;
			this.ExperienceLabel.Text = viewModel.Experience;
			this.ReviewLabel.Text = viewModel.Reviews;
			this.AvailabilityLabel.Text = viewModel.Availability;
			this.DistanceLabel.Text = viewModel.Distance;

			if(viewModel.ShowFooter)
			{
				this.SuperlativeImageView.Image = UIImage.FromBundle (viewModel.SuperlativeImageName);
				this.SuperlativeLabel.Text = viewModel.Superlative;
				this.MoreLabel.Text = viewModel.More;
//				this.SuperlativeViewHeightConstraint.Constant = 51;
//				this.SuperlativeViewHeightConstraint.Priority = 250;
			}
			else
			{
//				this.SuperlativeViewHeightConstraint.Constant = 0;
//				this.SuperlativeViewHeightConstraint.Priority = 1001;
			}

			this.CostTitleLabel.Hidden = !viewModel.ShowCost;
			this.CostValueLabel.Hidden = !viewModel.ShowCost;
			this.CostValueLabel.Text = viewModel.Cost;
			this.GenderImageView.Image = UIImage.FromBundle (viewModel.MainImageName);
			this.GenderImageViewHeightConstraint.Constant = viewModel.IsPremier ? 78 : 45;	
			this.NameLabel.TextColor = viewModel.TitleColor.ToUIColor();
			this.SuperlativeLabel.TextColor = viewModel.SuperlativeColor.ToUIColor ();
			this.SideView.BackgroundColor = viewModel.SideBarColor.ToUIColor ();

			this.AvailabilityLabel.TextColor = SharedColors.Black.ToUIColor();
			this.CostValueLabel.TextColor = SharedColors.Black.ToUIColor ();
			this.ExperienceLabel.TextColor = SharedColors.Black.ToUIColor ();
			this.DistanceLabel.TextColor = SharedColors.Black.ToUIColor ();

			_touchUpInside = touchUpAction;

			if(viewModel.HideStarRatingControl)
			{
				StarViewWidthConstraint.Constant = 0;
				StarViewRightConstraint.Constant = 0;
			}
			else
			{
				StarViewWidthConstraint.Constant = 70;
				StarViewRightConstraint.Constant = 10;
			}
		}
	}
}
