// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.VM;

namespace iOS.Phone
{
	public partial class DrRecHeaderCell : UITableViewCell
	{
		private Action<object, EventArgs> _touchUpInside { get; set; }

		public static string Key = new NSString("DrRecHeaderCell");

		public DrRecHeaderCell (IntPtr handle) : base (handle) { }

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			LearnMoreButton.TouchUpInside += OnTouchUpInside;
		}

		public nfloat CalculateHeight()
		{
			return 110;
		}

		public void Configure (nint section, BaseRecommendationListViewModel viewModel)
		{
			// Configure UI elements
			if(section == 1)
			{
				TitleView.BackgroundColor = viewModel.MainRecSectionColor.ToUIColor ();
				ImageView.Image = UIImage.FromBundle (viewModel.MainRecSectionImageName);
				TitleLabel.Text = viewModel.MainRecSectionHeaderText;
				TitleLabel.TextColor = SharedColors.White.ToUIColor ();
				SubtitleLabel.Text = viewModel.MainRecSectionSubHeaderText;
			} 
			else if (section == 2)
			{
				TitleView.BackgroundColor = viewModel.OtherRecSectionColor.ToUIColor ();
				ImageView.Image = UIImage.FromBundle(viewModel.OtherRecSectionImageName);
				TitleLabel.Text = viewModel.OtherRecSectionHeaderText;
				TitleLabel.TextColor = SharedColors.Black.ToUIColor ();
				SubtitleLabel.Text = viewModel.OtherRecSectionSubHeaderText;
			}
			this.UserInteractionEnabled = false;
			this.TitleView.Frame = new CoreGraphics.CGRect (0, 0, 1000, 40); 
			this.Frame = new CoreGraphics.CGRect (0, 0, 1000, this.CalculateHeight ()); 
			this.ContentView.Frame = new CoreGraphics.CGRect (0, 0, 1000, this.CalculateHeight ()); 
		}

		private void OnTouchUpInside (object sender, EventArgs args)
		{
			if(_touchUpInside != null)
			{
				_touchUpInside (this, args);
			}
		}
	}
}
