// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class PSButtonCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString ("PSButtonCell");

		public event EventHandler TouchUpInside
		{
			add { CellButton.TouchUpInside += value; }
			remove { CellButton.TouchUpInside -= value; }
		}

		public string ButtonText {
			get{ return CellButton.TitleLabel.Text; }
			set{ CellButton.SetTitle (value, UIControlState.Normal); }
		}

		public PSButtonCell (IntPtr handle) : base (handle)
		{
		}
	}
}
