// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class PSThreeButtonCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString ("PSThreeButtonCell");

		#region Private Variables

		private Action _leftButtonAction;
		private Action _centerButtonAction;
		private Action _rightButtonAction;

		#endregion

		#region Member Properties

		public Action LeftButtonAction
		{
			get { return _leftButtonAction; }
			set 
			{ 
				LeftButton.TouchUpInside -= LeftButtonActionExecute; 
				LeftButton.TouchUpInside += LeftButtonActionExecute;
				_leftButtonAction = value;
			}
		}

		public Action CenterButtonAction
		{
			get { return _centerButtonAction; }
			set 
			{ 
				CenterButton.TouchUpInside -= LeftButtonActionExecute; 
				CenterButton.TouchUpInside += LeftButtonActionExecute;
				_centerButtonAction = value;
			}
		}

		public Action RightButtonAction
		{
			get { return _rightButtonAction; }
			set 
			{ 
				RightButton.TouchUpInside -= LeftButtonActionExecute; 
				RightButton.TouchUpInside += LeftButtonActionExecute;
				_rightButtonAction = value;
			}
		}

		#endregion

		#region Methods

		public PSThreeButtonCell (IntPtr handle) : base (handle) { }

		private void LeftButtonActionExecute (object sender, EventArgs args)
		{
			if(LeftButtonAction != null)
			{
				LeftButtonAction ();
			}
		}

		private void CenterButtonActionExecute (object sender, EventArgs args)
		{
			if(CenterButtonAction != null)
			{
				CenterButtonAction ();
			}
		}

		private void RightButtonActionExecute (object sender, EventArgs args)
		{
			if(RightButtonAction != null)
			{
				RightButtonAction ();
			}
		}

		#endregion
	}
}
