// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class PSTwoButtonCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString ("PSTwoButtonCell");

		public PSTwoButtonCell (IntPtr handle) : base (handle)
		{
		}

		public event EventHandler LeftButtonTouchUpInside
		{
			add { LeftButton.TouchUpInside += value; }
			remove { LeftButton.TouchUpInside -= value; }
		}

		public event EventHandler RightButtonTouchUpInside
		{
			add { RightButton.TouchUpInside += value; }
			remove { RightButton.TouchUpInside -= value; }
		}


		public string LeftButtonText {
			get{ return LeftButton.TitleLabel.Text; }
			set{ LeftButton.SetTitle (value, UIControlState.Normal); }
		}

		public string RightButtonText {
			get{ return RightButton.TitleLabel.Text; }
			set{ RightButton.SetTitle (value, UIControlState.Normal); }
		}
	}
}
