// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using System.Linq;
using Shared.Common.Models.TuringTree;

namespace iOS.Phone
{
	public partial class SurveyCellOneButton : BaseSurveyButtonCell
	{
		public static NSString Key = new NSString ("SurveyCellOneButton");

		#region Methods

		public SurveyCellOneButton (IntPtr handle) : base (handle) { }

		protected override void InitBindings ()
		{
			var action = Section.SectionActions.ElementAt(IndexPath.Row);

			Button.SetTitle(action.ActionLabel, UIControlState.Normal);

			Button.TouchUpInside -= OnCenterButtonTouchUpInside;
			Button.TouchUpInside += OnCenterButtonTouchUpInside;

			SetButtonDefaultEnabledState (Button, action);
		}

		public override void OnCanExecute (bool canExecute, GenericAction action)
		{
			Button.Enabled = canExecute;
		}

		#endregion
	}
}
