// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.Common.Models.TuringTree;
using System.Linq;

namespace iOS.Phone
{
	public partial class SurveyCellCheckmark : BaseSurveyCell
	{
		public static NSString Key = new NSString ("SurveyCellCheckmark");

		#region Methods

		public SurveyCellCheckmark (IntPtr handle) : base (handle) { }	

		protected override void InitBindings ()
		{
			var action = Section.SectionActions.ElementAt (IndexPath.Row);

			TitleLabel.Text = action.ActionLabel;
			AccessoryImageView.Image = action.Selected ? UIImage.FromFile ("Checkmark.png") : null;
			ContentView.BackgroundColor = action.Selected ? SharedColors.Yellow.ToUIColor () : SharedColors.White.ToUIColor ();
		}

		public override void OnDeselected (UITableView tableView, NSIndexPath indexPath)
		{
			base.OnDeselected (tableView, indexPath);

			AccessoryImageView.Image = null;
			ContentView.BackgroundColor = SharedColors.White.ToUIColor ();

			OnTouchUpInside (this, Section.SectionActions.ElementAt (IndexPath.Row));
		}

		public override void OnSelected (UITableView tableView, NSIndexPath indexPath)
		{
			base.OnSelected (tableView, indexPath);

			AccessoryImageView.Image = UIImage.FromFile ("Checkmark.png");
			ContentView.BackgroundColor = SharedColors.Yellow.ToUIColor ();

			OnTouchUpInside (this, Section.SectionActions.ElementAt (IndexPath.Row));
		}

		#endregion
	}
}
