// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using System.Linq;
using Shared.Common.Models.TuringTree;

namespace iOS.Phone
{
	public partial class SurveyCellOneButtonLink : BaseSurveyButtonCell
	{
		public static NSString Key = new NSString ("SurveyCellOneButtonLink");

		#region Methods

		public SurveyCellOneButtonLink (IntPtr handle) : base (handle) { }

		protected override void InitBindings ()
		{
			var action = Section.SectionActions.ElementAt (IndexPath.Row);

			Button.SetTitle(action.ActionLabel, UIControlState.Normal);

			Button.TouchUpInside -= OnCenterButtonTouchUpInside;
			Button.TouchUpInside += OnCenterButtonTouchUpInside;
		}

		#endregion
	}
}
