// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using System.Linq;
using Shared.Common.Models.TuringTree;

namespace iOS.Phone
{
	public partial class SurveyCellTwoButton : BaseSurveyButtonCell
	{
		public static NSString Key = new NSString ("SurveyCellTwoButton");

		#region Methods

		public SurveyCellTwoButton (IntPtr handle) : base (handle) {}

		protected override void InitBindings ()
		{
			var leftAction = Section.SectionActions.ElementAt (0);
			var rightAction = Section.SectionActions.ElementAt (1);

			LeftButton.SetTitle (leftAction.ActionLabel, UIControlState.Normal);
			RightButton.SetTitle (rightAction.ActionLabel, UIControlState.Normal);

			LeftButton.TouchUpInside -= OnLeftButtonTouchUpInside;
			RightButton.TouchUpInside -= OnRightButtonTouchUpInside;

			LeftButton.TouchUpInside += OnLeftButtonTouchUpInside;
			RightButton.TouchUpInside += OnRightButtonTouchUpInside;

			SetButtonDefaultEnabledState (LeftButton, leftAction);
			SetButtonDefaultEnabledState (RightButton, rightAction);
		}

		public override void OnCanExecute (bool canExecute, GenericAction action)
		{
			var index = Section.SectionActions.IndexOf (action);
			UIButton button = null;

			switch (index)
			{
			case 0:
				button = LeftButton;
				break;
			case 1:
				button = RightButton;
				break;
			}
			button.Enabled = canExecute;
		}

		#endregion
	}
}
