// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using System.Linq;
using Shared.Common.Models.TuringTree;

namespace iOS.Phone
{
	public partial class SurveyCellTwoButtonLink : BaseSurveyButtonCell
	{
		public static NSString Key = new NSString ("SurveyCellTwoButtonLink");

		#region Methods
	
		public SurveyCellTwoButtonLink (IntPtr handle) : base (handle) { }

		protected override void InitBindings ()
		{
			var leftAction = Section.SectionActions.ElementAt (0);
			var rightAction = Section.SectionActions.ElementAt (1);

			LeftButton.SetTitle (leftAction.ActionLabel, UIControlState.Normal);
			RightButton.SetTitle (rightAction.ActionLabel, UIControlState.Normal);

			LeftButton.TouchUpInside -= OnLeftButtonTouchUpInside;
			RightButton.TouchUpInside -= OnRightButtonTouchUpInside;

			LeftButton.TouchUpInside += OnLeftButtonTouchUpInside;
			RightButton.TouchUpInside += OnRightButtonTouchUpInside;
		}

		#endregion
	}
}
