// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.Common.Models.TuringTree;
using System.Linq;

namespace iOS.Phone
{
	public partial class SurveyCellDefault : BaseSurveyCell
	{
		public static NSString Key = new NSString ("SurveyCellDefault");

		#region Methods

		public SurveyCellDefault (IntPtr handle) : base (handle) { }

		protected override void InitBindings ()
		{
			var action = Section.SectionActions.ElementAt (IndexPath.Row);

			TitleLabel.Text = action.ActionLabel;
		}

		public override void OnSelected (UITableView tableView, NSIndexPath indexPath)
		{
			base.OnSelected (tableView, indexPath);

			OnTouchUpInside (this, Section.SectionActions.ElementAt (IndexPath.Row));
		}

		#endregion
	}
}
