// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class DefaultCardCell : UITableViewCell
	{
		public DefaultCardCell (IntPtr handle) : base (handle)
		{
		}
	}
}
