// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;

namespace iOS.Phone
{
	public partial class GenericEditCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString ("GenericEditCell");

		public nfloat BottomConstraint
		{ 
			get { return SubtitleBottomConstraint.Constant; }
			set { SubtitleBottomConstraint.Constant = value; }
		}

		public string Title {
			get { return TitleLabel.Text; }
			set { TitleLabel.Text = value; }
		}

		public string Subtitle {
			get { return SubtitleLabel.Text; }
			set { SubtitleLabel.Text = value; }
		}

		private Action _touchUpAction;
		public Action TouchUpAction { get { return _touchUpAction;} set{
				ActionButton.TouchUpInside -= FireAction;
				ActionButton.TouchUpInside += FireAction;
				_touchUpAction = value;
			} }

		public event EventHandler Action
		{
			add 
			{ 
				ActionButton.TouchUpInside -= value;
				ActionButton.TouchUpInside += value; 
			}
			remove 
			{ 
				ActionButton.TouchUpInside -= value; 
			}
		}

		public GenericEditCell (IntPtr handle) : base (handle)
		{

		}

		void FireAction (object sender, EventArgs args)
		{
			if (TouchUpAction != null) {
				TouchUpAction ();
			}
		}
	}
}
