// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class HealthProQuestionCell : UITableViewCell
	{
		public static string Key = "HealthProQuestionCell";

		public string Question { get {return QuestionLabel.Text; } set { QuestionLabel.Text = value;} }

		public HealthProQuestionCell (IntPtr handle) : base (handle)
		{
		}
	}
}
