// This file has been autogenerated from a class added in the UI designer.

using System;

using .Foundation;
using UIKit;

namespace CompassMobile.iOS.Phone
{
	public partial class IncentivesListController : UIViewController
	{
		public IncentivesListController (IntPtr handle) : base (handle)
		{
		}
	}
}
