// This file has been autogenerated from a class added in the UI designer.

using System;

using .Foundation;
using UIKit;

namespace CompassMobile.iOS.Phone
{
	public partial class IncentivesListTableController : UITableViewController
	{
		public IncentivesListTableController (IntPtr handle) : base (handle)
		{
		}
	}
}
