// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class InsuranceController : UIViewController
	{
		public InsuranceController (IntPtr handle) : base (handle)
		{
		}
	}
}
