// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class LocationLookupCell : UITableViewCell
	{
		public LocationLookupCell (IntPtr handle) : base (handle)
		{
		}

		public string Title {
			get {
				return TitleLabel.Text;
			}
			set{
				TitleLabel.Text = value;
			}
		}

		public string Subtitle {
			get {
				return SubtitleLabel.Text;
			}
			set{
				SubtitleLabel.Text = value;
			}
		}			

		public UIColor TitleColor
		{
			get{
				return TitleLabel.TextColor;
			}

			set{
				TitleLabel.TextColor = value;
			}
		}


		public UIColor SubtitleColor
		{
			get{
				return SubtitleLabel.TextColor;
			}

			set{
				SubtitleLabel.TextColor = value;
			}
		}

	}
}
