// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common.Models.TuringTree;
using System.Collections.Generic;
using Shared.VM;
using Shared.Common;
using System.Threading.Tasks;

namespace iOS.Phone
{
	public partial class InterstitialController : UIViewController 
	{
		private InterstitialViewModel _viewModel;

		public FlowData FlowData { get; set; }
		public TreeMap TreeMap { get; set; }
		public PatientPreferences PatientPreferences { get; set; }

		public InterstitialController (IntPtr handle) : base (handle) { }

		public override async void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_viewModel = new InterstitialViewModel (FlowData, PatientPreferences);
			_viewModel.RequestFacilityRecommendationPage = OnRequestFacilityRecommendationPage;
			_viewModel.RequestDoctorRecommendationPage = OnRequestDoctorRecommendationPage;
			_viewModel.RequestCostEstimatePage = OnRequestCostEstimateRecommendationPage;

			NavigationController.SetNavigationBarHidden (true, true);

			await _viewModel.DidLoad ();
		}

		private void OnRequestFacilityRecommendationPage (FacilityRecommendation recommendation)
		{
			var container = UIApplication.SharedApplication.KeyWindow.RootViewController.FindViewControllerClass (typeof(HomeContainerController)) as HomeContainerController;
			var controller = new FacilityRecommendationController (recommendation, FlowData, TreeMap, PatientPreferences);
			var navController = new UINavigationController (controller);

			navController.ConfigureToCompassDefaults (true);
			container.CenterPanel = navController;
		}

		private void OnRequestDoctorRecommendationPage (DoctorRecommendation recommendation)
		{
			var container = UIApplication.SharedApplication.KeyWindow.RootViewController.FindViewControllerClass (typeof(HomeContainerController)) as HomeContainerController;
			var controller = new DoctorRecommendationController (recommendation, FlowData, TreeMap, PatientPreferences);
			var navController = new UINavigationController (controller);

			navController.ConfigureToCompassDefaults (true);
			container.CenterPanel = navController;
		}

		private void OnRequestCostEstimateRecommendationPage (DoctorRecommendation recommendation)
		{
			var container = UIApplication.SharedApplication.KeyWindow.RootViewController.FindViewControllerClass (typeof(HomeContainerController)) as HomeContainerController;
			var controller = new DoctorRecommendationController (recommendation, FlowData, TreeMap, PatientPreferences);
			var navController = new UINavigationController (controller);

			navController.ConfigureToCompassDefaults (true);
			container.CenterPanel = navController;
		}
	}
}
