// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.VM;

namespace iOS.Phone
{
	public partial class HealthProCardCell : BaseCardCell
	{
		public static NSString Key = new NSString("HealthProCardCell");

		public HealthProCardCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			ActionButton.TouchUpInside += OnActionButtonTapped;
			CallButton.TouchUpInside += OnCallButtonTapped;
			EmailButton.TouchUpInside += OnEmailButtonTapped;
		}

		public override nfloat CalculateHeight (BaseCardViewModel baseViewModel, bool isHeader = false)
		{
			return 180;
		}

		public override void Configure (BaseCardViewModel baseViewModel, bool isHeader = false)
		{
			base.Configure (baseViewModel);

			// TODO: Use the viewModel to populate properties on the cell
			ContainerView.Layer.BorderWidth = 1;

			if(isHeader)
			{ // shown behind the tableView's header
				ContainerView.Layer.BorderColor = SharedColors.Tan2.ToUIColor ().CGColor;
				ContainerViewBottomConstraint.Constant = 0;
				ContainerViewTopConstraint.Constant = 0;
				ContainerViewLeftConstraint.Constant = 0;
				ContainerViewRightConstraint.Constant = 0;
				UserInteractionEnabled = false;
			}
			else
			{ // shown in the body of the tableView
				ContainerView.Layer.BorderColor = SharedColors.LightGray.ToUIColor ().CGColor;	
				ContainerViewBottomConstraint.Constant = DefaultMargin/2;
				ContainerViewTopConstraint.Constant = DefaultMargin/2;
				ContainerViewLeftConstraint.Constant = DefaultMargin;
				ContainerViewRightConstraint.Constant = DefaultMargin;
				UserInteractionEnabled = true;
			}

			MainImageView.Layer.CornerRadius = MainImageView.Frame.Height / 2;

			ContentView.SetNeedsLayout ();
			ContentView.LayoutIfNeeded ();
		}

		private void OnActionButtonTapped (object sender, EventArgs args)
		{
			var alert = new UIAlertView ("Action Invoked", "Kabob", null, "Ok", null);
			alert.Show ();
		}

		private void OnCallButtonTapped (object sender, EventArgs args)
		{
			var alert = new UIAlertView ("Action Invoked", "Call", null, "Ok", null);
			alert.Show ();
		}

		private void OnEmailButtonTapped (object sender, EventArgs args)
		{
			var alert = new UIAlertView ("Action Invoked", "Email", null, "Ok", null);
			alert.Show ();
		}
	}
}
