// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class WebNavigationController : UINavigationController
	{
		public string WebsiteTitle {
			set { 
				if (ChildViewControllers.Length > 0 && ChildViewControllers [0] is WebViewController) {
					(ChildViewControllers [0] as WebViewController).Title = value;
				}
			}
		}

		public NSUrl InitWebsite {
			set { 
				if (ChildViewControllers.Length > 0 && ChildViewControllers [0] is WebViewController) {
					(ChildViewControllers [0] as WebViewController).InitWebsite = value;
				}
			}
		}

		public WebNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
