// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class WebViewController : UIViewController
	{
		public NSUrl InitWebsite {
			get;
			set;
		}

		public WebViewController (IntPtr handle) : base (handle)
		{
		}

		void ForwardButton_Clicked (object sender, EventArgs e)
		{
			if (WebView.CanGoForward) {
				if (WebView.IsLoading) {
					WebView.StopLoading();
				}
				WebView.GoForward();
			}
		}

		void BackButton_Clicked (object sender, EventArgs e)
		{
			if (WebView.CanGoBack) {
				if (WebView.IsLoading) {
					WebView.StopLoading();
				}
				WebView.GoBack();
			}
		}

		void RefreshButton_Clicked (object sender, EventArgs e)
		{
			WebView.Reload ();
		}

		void CloseButton_Clicked (object sender, EventArgs e)
		{
			if (WebView.IsLoading) {
				WebView.StopLoading();
			}
			DismissViewControllerAsync (true);
		}

		public void GoTo(NSUrl url)
		{
			WebView.LoadRequest(new NSUrlRequest(url));
		}
			
		private void WebView_LoadStarted (object sender, EventArgs e)
		{
			ActivityIndicator.StartAnimating();
		}

		private void WebView_LoadFinished (object sender, EventArgs e)
		{
			ActivityIndicator.StopAnimating();

			ForwardButton.Enabled = WebView.CanGoForward;

			BackButton.Enabled = WebView.CanGoBack;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			Toolbar.ConfigureToCompassDefaults ();

			ActivityIndicator.StopAnimating();

			ForwardButton.Enabled = false;

			BackButton.Enabled = false;

			WebView.LoadStarted += WebView_LoadStarted;
			WebView.LoadFinished += WebView_LoadFinished;
			RefreshButton.Clicked += RefreshButton_Clicked;
			CloseButton.Clicked += CloseButton_Clicked;
			BackButton.Clicked += BackButton_Clicked;
			ForwardButton.Clicked += ForwardButton_Clicked;

			if (InitWebsite != null) {
				GoTo (InitWebsite);
			}
		}

	}
}
