// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;

namespace iOS.Phone
{
	public partial class AddressCell : BaseRecommendationDetailCell
	{
		public static NSString Key = new NSString ("AddressCell");
		private DoctorRecommendationDetailAvailabilityViewModel _viewModel;

		public AddressCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			CallButton.TouchUpInside += OnCallButtonTapped;
			DirectionsButton.TouchUpInside += OnDirectionsButtonTapped;
		}

		public override void Configure (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			_viewModel = (DoctorRecommendationDetailAvailabilityViewModel)itemViewModel;

			CallButton.SetTitle (_viewModel.Phone, UIControlState.Normal);
			AddressLabel.Text = _viewModel.Address;
			DistanceLabel.Text = _viewModel.Distance;
		}

		private void OnCallButtonTapped (object sender, EventArgs args)
		{
			_viewModel.CallCommand.Execute (null);
		}

		private void OnDirectionsButtonTapped (object sender, EventArgs args)
		{
			_viewModel.DirectionsCommand.Execute (null);
		}
	}
}
