// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;

namespace iOS.Phone
{
	public partial class BasicHeaderCell : BaseRecommendationDetailCell
	{
		public static NSString Key = new NSString ("BasicHeaderCell");

		public BasicHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public override void Configure (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			var viewModel = (DoctorRecommendationDetailHeaderViewModel)itemViewModel;

			TitleLabel.Text = viewModel.Title;
			MainImageView.Image = UIImage.FromFile (viewModel.ImageName);
			BackgroundView.BackgroundColor = viewModel.Color.ToUIColor ();

			this.UserInteractionEnabled = false;
		}

		public override nfloat CalculateHeight (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			return 87;
		}
	}
}
