// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using CoreGraphics;

namespace iOS.Phone
{
	public partial class DrActionCell : BaseRecommendationDetailCell
	{
		public static NSString Key = new NSString ("DrActionCell");
		private DoctorRecommendationDetailActionViewModel _viewModel;
		private bool _isFirstLoad = true;

		public DrActionCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			AddRemoveButton.TouchUpInside += OnAddRemoveButtonTapped;
			CallButton.TouchUpInside += OnCallButtonTapped;
			ScheduleButton.TouchUpInside += OnScheduleButtonTapped;
		}

		public override nfloat CalculateHeight (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			return 58;
		}

		public override void Configure (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			if (_isFirstLoad == false)
				return;
			
			_viewModel = (DoctorRecommendationDetailActionViewModel)itemViewModel;

			_viewModel.RequestAddRemovePageUpdate += OnRequestAddRemovePageUpdate;
			OnRequestAddRemovePageUpdate (null, new AddRemoveEventArgs(_viewModel.IsMyDoctor, _viewModel.AddRemoveText));

			_isFirstLoad = false;
		}

		private void OnAddRemoveButtonTapped (object sender, EventArgs args)
		{
			_viewModel.AddRemoveCommand.Execute (null);
		}

		private void OnCallButtonTapped (object sender, EventArgs args)
		{
			_viewModel.CallCommand.Execute (null);
		}

		private void OnScheduleButtonTapped (object sender, EventArgs args)
		{
			_viewModel.ScheduleCommand.Execute (null);
		}

		private void OnRequestAddRemovePageUpdate (object sender, AddRemoveEventArgs args)
		{
			AddRemoveLabel.Text = args.Text;
			AddRemoveLabel.Alpha = 0;

			UIView.AnimateNotify (0.5, 0, 0.4f, 1, 0, () => {

				AddRemoveButton.Transform = CGAffineTransform.MakeRotation (args.IsMyDoctor ? (nfloat)Math.PI / 4f : 0);
				AddRemoveLabel.Alpha = 1;
			}, (res) =>{});
		}
	}
}
