// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;

namespace iOS.Phone
{
	public partial class FacilityPrivilegesCell : BaseRecommendationDetailCell
	{
		public static NSString Key = new NSString ("FacilityPrivilegesCell");

		public FacilityPrivilegesCell (IntPtr handle) : base (handle)
		{
		}

		public override void Configure (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			var viewModel = (DoctorRecommendationDetailFacilityViewModel)itemViewModel;

			NameLabel.Text = viewModel.Title;
			PhoneLabel.Text = viewModel.PhoneNumber;
			AddressLabel.Text = viewModel.Address;
			SuperlativeImageView.Image = UIImage.FromFile (viewModel.SuperlativeImageName);
			SuperlativeLabel.Text = viewModel.Superlative;
			DistanceLabel.Text = viewModel.Distance;
			CostTitleLabel.Hidden = !viewModel.ShowCost;
			CostValueLabel.Hidden = !viewModel.ShowCost;
			CostValueLabel.Text = viewModel.Cost;
			SideView.BackgroundColor = viewModel.SideColor.ToUIColor ();

			if(!viewModel.ShowPathologistAndFees)
			{
				InfoLabel.Text = String.Empty;
				InfoLabel.Hidden = true;
				InfoImageView.Hidden = true;	
				InfoLabelBottomConstraint.Constant = 0;
				InfoLabelTopConstraint.Constant = 5;

				ContentView.SetNeedsLayout ();
				ContentView.LayoutIfNeeded ();
			}
			else
			{
				InfoLabel.Hidden = false;
				InfoImageView.Hidden = false;	
			}

			_expandingLabels.Add (SuperlativeLabel);

			this.ContentView.SetNeedsLayout ();
			this.ContentView.LayoutIfNeeded ();
		}
	}
}
