// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;

namespace iOS.Phone
{
	public partial class FacilityToDoctorRecommendationCell : BaseRecommendationDetailCell
	{
		public static NSString Key = new NSString("FacilityToDoctorRecommendationCell");
		private FacilityToDoctorRecommendationViewModel _viewModel;

		public FacilityToDoctorRecommendationCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			RecommendButton.TouchUpInside += (sender, e) => _viewModel.RecommendationCommand.Execute(null);
		}

		public override void Configure (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			_viewModel = (FacilityToDoctorRecommendationViewModel)itemViewModel;
		}
	}
}
