// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;

namespace iOS.Phone
{
	public partial class FacilityRecCell : BaseRecommendationCell
	{
		public static NSString Key = new NSString("FacilityRecCell");

		public FacilityRecCell (IntPtr handle) : base (handle) { }

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			this.ActionButton.TouchUpInside += OnTouchUpInside;
		}
			
		public override void Configure (BaseRecommendationListItemViewModel baseVM, Action<object, EventArgs> touchUpAction)
		{
			var viewModel = (FacilityRecommendationListItemViewModel)baseVM;

			_touchUpInside = touchUpAction;

			this.MainImageView.Image = UIImage.FromFile (viewModel.MainImageName);
			this.ImageViewHeightConstraint.Constant = viewModel.IsPremier ? 78 : 45;
			this.NameLabel.Text = viewModel.Title;
			this.SubtitleLabel.Text = viewModel.SubTitle;
			this.MainImageView.Image = UIImage.FromBundle (viewModel.MainImageName);
			this.CostTitleLabel.Hidden = !viewModel.ShowCost;
			this.CostValueLabel.Hidden = !viewModel.ShowCost;
			this.CostValueLabel.Text = viewModel.Cost;
			this.NameLabel.TextColor = viewModel.TitleColor.ToUIColor();
			this.SuperlativeLabel.TextColor = viewModel.SuperlativeColor.ToUIColor ();
			this.SideView.BackgroundColor = viewModel.SideBarColor.ToUIColor ();
			this.SuperlativeImageView.Image = UIImage.FromBundle (viewModel.SuperlativeImageName);
			this.SuperlativeLabel.Text = viewModel.Superlative;
			this.MoreLabel.Text = viewModel.More;
			this.AccreditedLabel.Text = viewModel.AccreditedText;
			this.DistanceLabel.Text = viewModel.Distance;

			this.DistanceLabel.TextColor = SharedColors.Black.ToUIColor ();
			this.CostValueLabel.TextColor = SharedColors.Black.ToUIColor ();

			if(!String.IsNullOrWhiteSpace(this.AccreditedLabel.Text))
			{
				var font = UIFont.FromName ("CenturyGothic-Bold", this.AccreditedLabel.Font.PointSize);
				var range = new NSRange(0, this.AccreditedLabel.Text.IndexOf(" "));
				var text = new NSMutableAttributedString (this.AccreditedLabel.Text);

				text.SetAttributes (new UIStringAttributes () { Font = font }, range);

				this.AccreditedLabel.AttributedText  = text;	
			}

			this.SeparatorView.Hidden = !viewModel.ShowFooter;

			_expandingLabels.Add (SuperlativeLabel);

			this.ContentView.SetNeedsLayout ();
			this.ContentView.LayoutIfNeeded ();
		}
	}
}
