// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;

namespace iOS.Phone
{
	public partial class FacilityBioSummaryCell : BaseRecommendationDetailCell
	{
		public static NSString Key = new NSString("FacilityBioSummaryCell");
		protected FacilityRecommendationDetailSummaryViewModel _viewModel;

		public FacilityBioSummaryCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			WebsiteButton.TouchUpInside += (sender, e) => _viewModel.WebsiteCommand.Execute(null);
			DirectionButton.TouchUpInside += (sender, e) => _viewModel.DirectionsCommand.Execute(null);
			PhoneButton.TouchUpInside += (sender, e) => _viewModel.CallCommand.Execute(null);
		}

		public override void Configure (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			_viewModel = (FacilityRecommendationDetailSummaryViewModel)itemViewModel;

			MainImageView.Image = UIImage.FromFile (_viewModel.MainImageName);
			ImageViewHieghtConstraint.Constant = _viewModel.IsPremier ? 78 : 45;
			NameLabel.Text = _viewModel.Name;
			SubtitleLabel.Text = _viewModel.Specialty;
			PhoneButton.SetTitle (_viewModel.PhoneNumber, UIControlState.Normal);
			CostTitleLabel.Hidden = !_viewModel.ShowCost;
			CostValueLabel.Hidden = !_viewModel.ShowCost;
			CostValueLabel.Text = _viewModel.Cost;
			AddressLabel.Text = _viewModel.Address;
			DistanceLabel.Text = _viewModel.Distance;

			if(!_viewModel.ShowWebsite)
			{
				WebsiteButton.Hidden = true;
				AddressBottomConstraint.Constant = 15;
			}

			this.ContentView.SetNeedsLayout ();
			this.ContentView.LayoutIfNeeded ();
		}
	}
}
