// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;

namespace iOS.Phone
{
	public partial class StaffCell : BaseRecommendationDetailCell
	{
		public static NSString Key = new NSString ("StaffCell");
		private DoctorRecommendationDetailStaffViewModel _viewModel;

		public StaffCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			ProgressView.LabelHidden = true;
			ProgressView.BackgroundColor = UIColor.Clear;

			ProgressView.BorderColor = UIColor.Clear;
			ProgressView.CornerRadius = 0;
			ProgressView.TrackTintColor = SharedColors.Gray5.ToUIColor ();
		}

		public override void Configure (BaseRecommendationDetailListItemViewModel itemViewModel)
		{
			_viewModel = (DoctorRecommendationDetailStaffViewModel)itemViewModel;

			RatingLabel.Text = _viewModel.Rating;
			ProgressView.Progress = (float)(_viewModel.RawRating / 5);
		}
	}
}
