#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Droid.Resource", IsApplication=false)]

namespace Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public static int ahBarColor = 2130771982;
			
			// aapt resource value: 0x7f010016
			public static int ahBarLength = 2130771990;
			
			// aapt resource value: 0x7f010015
			public static int ahBarWidth = 2130771989;
			
			// aapt resource value: 0x7f010013
			public static int ahCircleColor = 2130771987;
			
			// aapt resource value: 0x7f010012
			public static int ahDelayMillis = 2130771986;
			
			// aapt resource value: 0x7f010014
			public static int ahRadius = 2130771988;
			
			// aapt resource value: 0x7f01000f
			public static int ahRimColor = 2130771983;
			
			// aapt resource value: 0x7f010010
			public static int ahRimWidth = 2130771984;
			
			// aapt resource value: 0x7f010011
			public static int ahSpinSpeed = 2130771985;
			
			// aapt resource value: 0x7f01000b
			public static int ahText = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int ahTextColor = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public static int ahTextSize = 2130771981;
			
			// aapt resource value: 0x7f010009
			public static int customFont = 2130771977;
			
			// aapt resource value: 0x7f010008
			public static int fletCustomPicker = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int fletDatePicker = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int fletDisplayToolTip = 2130771974;
			
			// aapt resource value: 0x7f010001
			public static int fletPadding = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int fletPaddingBottom = 2130771973;
			
			// aapt resource value: 0x7f010002
			public static int fletPaddingLeft = 2130771970;
			
			// aapt resource value: 0x7f010004
			public static int fletPaddingRight = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int fletPaddingTop = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int fletTextAppearance = 2130771968;
			
			// aapt resource value: 0x7f01000a
			public static int parallaxOffset = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040002
			public static int flet_hint_margin = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int flet_hint_text_padding_horizontal = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int flet_hint_text_size = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int hide = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_action_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_action_cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ic_action_forward = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int ic_action_refresh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int ic_clear = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int ic_errorstatus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int ic_successstatus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int ic_tooltip = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int LargeCheck = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int LargeWhiteCheck = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int LargeX = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int pin_current = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int pin_default = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int pin_done = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int roundedbg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int roundedbgdark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int show = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public static int browser_acitivityIndicator = 2131099657;
			
			// aapt resource value: 0x7f060007
			public static int browser_backButon = 2131099655;
			
			// aapt resource value: 0x7f060005
			public static int browser_bottomBar = 2131099653;
			
			// aapt resource value: 0x7f060003
			public static int browser_close = 2131099651;
			
			// aapt resource value: 0x7f060008
			public static int browser_forwardButton = 2131099656;
			
			// aapt resource value: 0x7f060006
			public static int browser_navButtons = 2131099654;
			
			// aapt resource value: 0x7f060001
			public static int browser_refresh = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int browser_title = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int browser_topBar = 2131099648;
			
			// aapt resource value: 0x7f060004
			public static int browser_webView = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public static int feedbackPopupImage = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public static int feedbackPopupLayout = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public static int feedbackPopupText = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public static int loadingImage = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public static int loadingProgressBar = 2131099661;
			
			// aapt resource value: 0x7f060010
			public static int loadingProgressWheel = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public static int textViewStatus = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int Browser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int FeedbackPopup = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int loading = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int loadingimage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int loadingprogress = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public static int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomFonts = new int[] {
					2130771977};
			
			// aapt resource value: 0
			public static int CustomFonts_customFont = 0;
			
			public static int[] FloatLabeledEditText = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 8
			public static int FloatLabeledEditText_fletCustomPicker = 8;
			
			// aapt resource value: 7
			public static int FloatLabeledEditText_fletDatePicker = 7;
			
			// aapt resource value: 6
			public static int FloatLabeledEditText_fletDisplayToolTip = 6;
			
			// aapt resource value: 1
			public static int FloatLabeledEditText_fletPadding = 1;
			
			// aapt resource value: 5
			public static int FloatLabeledEditText_fletPaddingBottom = 5;
			
			// aapt resource value: 2
			public static int FloatLabeledEditText_fletPaddingLeft = 2;
			
			// aapt resource value: 4
			public static int FloatLabeledEditText_fletPaddingRight = 4;
			
			// aapt resource value: 3
			public static int FloatLabeledEditText_fletPaddingTop = 3;
			
			// aapt resource value: 0
			public static int FloatLabeledEditText_fletTextAppearance = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 3
			public static int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public static int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public static int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public static int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public static int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public static int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public static int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public static int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public static int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public static int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public static int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public static int ProgressWheel_ahTextSize = 2;
			
			public static int[] parallaxscrollview = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public static int parallaxscrollview_parallaxOffset = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
