// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Linq;
using Shared.Common;
using Shared.VM;

namespace iOS.Phone
{
	public partial class CompletedIncentivesHeaderCell : UITableViewCell
	{
		public static readonly string Key = "CompletedIncentivesHeaderCell";

		public CompletedIncentivesHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public void Configure(IncentiveSummaryViewModel viewModel)
		{
			var frame = Frame;
			frame.Height = 163;
			Frame = frame;

			TodoCountLabel.Text = viewModel.UncompletedActionCount.ToString ();
			PremiumEarnedLabel.Text = String.Format ("${0}", viewModel.EarnedOffPremiumAmount);
			PremiumEarnedTextLabel.Text = viewModel.EarnedOffPremiumText;

			PointsEarnedLabel.Text = String.Format ("${0}", viewModel.EarnedPayoutAmout);
			PointsEarnedTextLabel.Text = viewModel.EarnedPayoutText;

			viewModel.PropertyChanged += (object sender, System.ComponentModel.PropertyChangedEventArgs e) => 
			{
				if (e.PropertyName.Equals("UncompletedActionCount"))
				{
					TodoCountLabel.Text = viewModel.UncompletedActionCount.ToString();
				}
			};

			viewModel.PropertyChanged += (object sender, System.ComponentModel.PropertyChangedEventArgs e) => 
			{
				if (e.PropertyName.Equals("EarnedOffPremiumAmount"))
				{
					TodoCountLabel.Text = String.Format ("${0}",viewModel.EarnedOffPremiumAmount);
				}
			};

			viewModel.PropertyChanged += (object sender, System.ComponentModel.PropertyChangedEventArgs e) => 
			{
				if (e.PropertyName.Equals("EarnedPayoutAmout"))
				{
					TodoCountLabel.Text = String.Format ("${0}",viewModel.EarnedPayoutAmout);

				}
			};
		}
	}
}
