// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using System.Linq;

namespace iOS.Phone
{
	public partial class IncentiveDefaultCell : UITableViewCell
	{
		public static readonly string Key = "IncentiveDefaultCell";
		public const string DATE_FORMAT = "MM/dd/yy";

		public IncentiveDefaultCell (IntPtr handle) : base (handle)
		{
		}

		public void Configure (IncentiveAction incentiveAction, Incentive incentive)
		{
			TitleLabel.Text = incentiveAction.Name;
			TopSeparatorView.Hidden = true;

			if(incentiveAction.Reward != null && incentiveAction.Reward.Award != 0)
			{
				AmountDetailLabel.Text = incentiveAction.Reward.TypeLabel;
				AmountLabel.Text = String.Format ("${0}", incentiveAction.Reward.Award);
			}
			else
			{
				AmountDetailLabel.Text = String.Empty;
				AmountLabel.Text = String.Empty;
			}

			if(incentiveAction.IsComplete)
			{
				if (incentiveAction.CompletedDate != null && incentiveAction.CompletedDate.HasValue) {
					SubtitleLabel.Text = String.Format ("Completed on {0}", incentiveAction.CompletedDate.Value.ToString (DATE_FORMAT));
				} else {
					SubtitleLabel.Text = String.Empty;
				}
				IconImageView.Image = UIImage.FromFile ("GreenCheckBox");
				SubtitleLabel.TextColor = TitleLabel.TextColor;
			}
			else
			{

				if(incentiveAction.IsExpired)
				{
					//TODO web service does not return an expired date. Can we just not print any date out?
					SubtitleLabel.Text = String.Format ("Expired on {0}", incentiveAction.DueDate.ToString(DATE_FORMAT));
					IconImageView.Image = UIImage.FromFile ("EmptyCheckBox");
					SubtitleLabel.TextColor = TitleLabel.TextColor;
				}
				else if(incentiveAction.IsUrgent() && incentiveAction.IsComplete == false)
				{
					SubtitleLabel.Text = String.Format ("Due by {0}", incentiveAction.DueDate.ToString(DATE_FORMAT));
					IconImageView.Image = UIImage.FromFile ("EmptyCheckBox");
					SubtitleLabel.TextColor = SharedColors.Orange.ToUIColor ();
				}
				else
				{
					SubtitleLabel.Text = String.Format ("Due by {0}", incentiveAction.DueDate.ToString(DATE_FORMAT));
					IconImageView.Image = UIImage.FromFile ("EmptyCheckBox");
					SubtitleLabel.TextColor = TitleLabel.TextColor;
				}
			}
			// last incentive active
			if(incentiveAction.Equals(incentive.Actions[incentive.Actions.Count - 1]))
			{
				BottomSeparatorViewTrailingConstraint.Constant = 0;
				BottomSparatorViewLeadingConstraint.Constant = 0;
			}
			else
			{
				BottomSeparatorViewTrailingConstraint.Constant = 18;
				BottomSparatorViewLeadingConstraint.Constant = 18;
			}
		}
	}
}
