// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using System.Linq;

namespace iOS.Phone
{
	public partial class IncentiveSectionCell : UITableViewCell
	{
		public static readonly string Key = "IncentiveSectionCell";

		public IncentiveSectionCell (IntPtr handle) : base (handle)
		{
		}

		public void Configure (Incentive incentive)
		{
			TitleLabel.Text = incentive.Name;

			if(incentive.Reward != null)
			{
				AmountDetailLabel.Text = incentive.Reward.TypeLabel;
				AmountLabel.Text = String.Format ("${0}", incentive.Reward.Award);
			}
			else
			{
				if(incentive.Actions != null)
				{
					AmountLabel.Text = String.Format ("${0}", incentive.Actions.Sum (a => a.Reward.Award));
					AmountDetailLabel.Text = incentive.Actions [0].Reward.TypeLabel;
				}
				else
				{
					AmountDetailLabel.Text = String.Empty;
					AmountLabel.Text = String.Empty;
				}
			}

			if(incentive.IsExpired && !incentive.IsComplete){
				SubtitleLabel.Text = String.Format ("Expired on {0}", incentive.EndDate.ToString("MM/dd/yy"));
			}
			else if(!incentive.IsComplete && incentive.Actions != null)
			{
				var completeCount = incentive.Actions.Where (a => a.IsComplete == true).ToList().Count;

				SubtitleLabel.Text = String.Format ("Complete {0} of {1} actions", incentive.Actions.Count - completeCount, incentive.Actions.Count);
				BottomSeparatorView.BackgroundColor = SharedColors.LightOrange.ToUIColor ();

				if (!incentive.IsComplete && incentive.IsUrgent ()) {
					IconImageView.Image = UIImage.FromFile ("OrangeClock.png");
				} else if (!incentive.IsComplete) {
					IconImageView.Image = UIImage.FromFile ("OrangeClock.png").AddColor (SharedColors.Tan2.ToUIColor ());
				} else {
					IconImageView.Image = UIImage.FromFile ("OrangeClock.png").AddColor (SharedColors.LightGreen.ToUIColor ());
				}

			}
			else
			{
				SubtitleLabel.Text = String.Format ("Completed on {0}", incentive.CompletedDate.Value.ToString("MM/dd/yy"));
				BottomSeparatorView.BackgroundColor = SharedColors.Tan2.ToUIColor ();
				IconImageView.Image = UIImage.FromFile ("GreenCheckBox.png");
			}


		}
	}
}
