// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using ObjCRuntime;
using CoreGraphics;
using Shared.Common;


namespace iOS.Phone
{
	public partial class IncentiveHeaderCell : UITableViewCell
	{
		public static readonly string Key = "IncentiveHeaderCell";

		public IncentiveHeaderCell (IntPtr handle) : base (handle) {}

		public void Configure (IncentiveSummarySectionType sectionType)
		{
			switch (sectionType)
			{
			case IncentiveSummarySectionType.UncompletedIncentives:
				IconImageView.Image = UIImage.FromFile ("IncentiveCoins");
				TitleLabel.Text = ApplicationResources.IncentiveSummaryUncompletedTitle;
				SubtitleLabel.Text = ApplicationResources.IncentiveSummaryUncompletedSubtitle;
				TitleView.BackgroundColor = SharedColors.LightGreen.ToUIColor ();
				TitleLabel.TextColor = SharedColors.DarkGreen.ToUIColor();
				break;
			case IncentiveSummarySectionType.CompletedIncentives:
				IconImageView.Image = UIImage.FromFile ("IncentiveCoins");
				TitleLabel.Text = ApplicationResources.IncentiveSummaryCompletedTitle;
				SubtitleLabel.Text = String.Empty;
				TitleView.BackgroundColor = SharedColors.LightGreen.ToUIColor();
				TitleLabel.TextColor = SharedColors.DarkGreen.ToUIColor();
				break;
			case IncentiveSummarySectionType.RecommendedActions:
				IconImageView.Image = UIImage.FromFile ("RecommendedHeart");
				TitleLabel.Text = ApplicationResources.RecommendationSummaryTitle; 
				SubtitleLabel.Text = ApplicationResources.RecommendationSummarySubtitle; 
				TitleView.BackgroundColor = SharedColors.CompassBlue.ToUIColor ();
				TitleLabel.TextColor = SharedColors.White.ToUIColor ();
				break;
			}
		}

		public nfloat CalculateHeight (IncentiveSummarySectionType sectionType)
		{
			var height = 0;

			switch (sectionType)
			{
			case IncentiveSummarySectionType.UncompletedIncentives:
				height = 125;
				break;
			case IncentiveSummarySectionType.CompletedIncentives:
				height = 80;
				break;
			case IncentiveSummarySectionType.RecommendedActions:
				height = 125;
				break;
			}
			return height;
		}

		public void Test ()
		{
//		TopSe
		}
	}
}
