// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.VM;
using System.Linq;

namespace iOS.Phone
{
	public partial class RecommendedActionCell : UITableViewCell
	{
		public static readonly string Key = "RecommendedActionCell";
		public const string DATE_FORMAT = "MM/dd/yy";

		public RecommendedActionCell (IntPtr handle) : base (handle)
		{
		}

		public void Configure(Incentive incentive, IncentiveSummaryViewModel viewModel)
		{
			TitleLabel.Text = incentive.Name;

			if(incentive.IsComplete)
			{
				if (incentive.CompletedDate != null && incentive.CompletedDate.HasValue) {
					SubtitleLabel.Text = String.Format ("Completed on {0}", incentive.CompletedDate.Value.ToString (DATE_FORMAT));
				} else {
					SubtitleLabel.Text = String.Empty;
				}

				IconImageView.Image = UIImage.FromFile ("GreenCheckBox");
			}
			else
			{
				// TODO: Need scheduled date
				IconImageView.Image = UIImage.FromFile ("EmptyCheckBox");
				SubtitleLabel.Text = String.Format ("Scheduled for {0}", incentive.EndDate.ToString (DATE_FORMAT));
			}

			var first = viewModel.OrderedIncentivesAndRecommendedActions.Where ( i => i.IsRequired == false).FirstOrDefault();
			var last = viewModel.OrderedIncentivesAndRecommendedActions.Where(i => i.IsRequired == false).LastOrDefault ();

			if(incentive.Actions.Count < 2)
			{
				TopSeparatorView.Hidden = false;
				BottomSeparatorViewLeadingConstraint.Constant = 0;
				BottomSeparatorViewTrailingConstraint.Constant = 0;
			}
			else if(first.Equals(incentive))
			{
				TopSeparatorView.Hidden = false;
//				BottomSeparatorView.Hidden = true;
				BottomSeparatorViewLeadingConstraint.Constant = 18;
				BottomSeparatorViewTrailingConstraint.Constant = 18;
			}
			else if(last.Equals(incentive))
			{
				TopSeparatorView.Hidden = true;
				BottomSeparatorViewLeadingConstraint.Constant = 0;
				BottomSeparatorViewTrailingConstraint.Constant = 0;
			}
			else
			{
				TopSeparatorView.Hidden = true;
				BottomSeparatorViewLeadingConstraint.Constant = 18;
				BottomSeparatorViewTrailingConstraint.Constant = 18;
			}
		}

		public void Configure (IncentiveAction incentiveAction, Incentive incentive)
		{
			TitleLabel.Text = incentiveAction.Name;


			if(incentiveAction.IsComplete)
			{
				IconImageView.Image = UIImage.FromFile ("GreenCheckBox");

				if (incentiveAction.CompletedDate != null && incentiveAction.CompletedDate.HasValue) {
					SubtitleLabel.Text = String.Format ("Completed on {0}", incentiveAction.CompletedDate.Value.ToString (DATE_FORMAT));
				} else {
					SubtitleLabel.Text = String.Empty;
				}
			}
			else
			{
				IconImageView.Image = UIImage.FromFile ("EmptyCheckBox");
				SubtitleLabel.Text = String.Format ("Due by {0}", incentiveAction.DueDate.ToString (DATE_FORMAT));
			}
				
			if(incentive.Actions.Count > 1)
			{
				// First
				if(incentiveAction.Equals(incentive.Actions[0]))
				{
					TopSeparatorView.Hidden = false;
					BottomSeparatorViewLeadingConstraint.Constant = 18;
					BottomSeparatorViewTrailingConstraint.Constant = 18;
				}
				// Last
				else if(incentiveAction.Equals(incentive.Actions[incentive.Actions.Count - 1]))
				{
					TopSeparatorView.Hidden = true;
					BottomSeparatorViewLeadingConstraint.Constant = 0;
					BottomSeparatorViewTrailingConstraint.Constant = 0;
				}
				// Middle
				else 
				{
					TopSeparatorView.Hidden = true;
					BottomSeparatorViewLeadingConstraint.Constant = 18;
					BottomSeparatorViewTrailingConstraint.Constant = 18;
				}
			}
			else
			{
				TopSeparatorView.Hidden = false;
				BottomSeparatorViewLeadingConstraint.Constant = 0;
				BottomSeparatorViewTrailingConstraint.Constant = 0;
			}
		}
	}
}
