// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.VM;
using GalaSoft.MvvmLight.Helpers;

namespace iOS.Phone
{
	public partial class RecommendationsHeaderCell : UITableViewCell
	{
		public static readonly string Key = "RecommendationsHeaderCell";

		public RecommendationsHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public void Configure(IncentiveSummaryViewModel viewModel)
		{
			var frame = Frame;
			frame.Height = 110;
			Frame = frame;

			TodoCountLabel.Text = viewModel.UncompletedActionCount.ToString ();

			viewModel.PropertyChanged += (object sender, System.ComponentModel.PropertyChangedEventArgs e) => 
			{
				if (e.PropertyName.Equals("UncompletedActionCount"))
				{
					TodoCountLabel.Text = viewModel.UncompletedActionCount.ToString();
				}
			};
		}
	}
}
