// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;

namespace iOS.Phone
{
	public partial class DefaultHeaderCell : BaseCell
	{
		#region Methods

		public DefaultHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			CircleView.Layer.CornerRadius = CircleView.Frame.Height / 2;
			CircleView.Layer.BorderColor = ThemeManager.Instance.CurrentTheme.PrimaryColor.ToUIColor().CGColor;
			CircleView.Layer.BorderWidth = 2;
		}

		protected override void ConfigureSubviews (IListItem item)
		{
			var viewModel = item as HeaderCardViewModel;

			TitleLabel.Text = viewModel.Time;
		}

		#endregion
	}
}
