// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;

namespace iOS.Phone
{
	public partial class DefaultHeaderCell : BaseCell
	{
		#region Methods

		public DefaultHeaderCell (IntPtr handle) : base (handle)
		{
		}

		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			CircleView.Layer.CornerRadius = CircleView.Frame.Height / 2;
			CircleView.Layer.BorderColor = ThemeManager.Instance.CurrentTheme.PrimaryColor.ToUIColor().CGColor;
			CircleView.Layer.BorderWidth = 2;

			UserInteractionEnabled = false;
		}

		protected override void ConfigureSubviews (IListItem item)
		{
			var viewModel = item as HeaderCardViewModel;

			TitleLabel.Text = viewModel.Title;

			if(viewModel.Position == Position.Top)
			{
				TimeLineViewTopConstraint.Constant = 18;
				TimeLineBottomConstraint.Constant = 0;
			}
			else if(viewModel.Position == Position.Middle)
			{
				TimeLineViewTopConstraint.Constant = 0;
				TimeLineBottomConstraint.Constant = 0;
			}
			else if(viewModel.Position == Position.Bottom)
			{
				TimeLineViewTopConstraint.Constant = 0;
				TimeLineBottomConstraint.Constant = 2;
			}
		}

		#endregion
	}
}
