// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;

namespace iOS.Phone
{
	public partial class HealthDetailsProcedurePromptController : BasePromptController
	{
		private HealthDetailsProcedurePromptViewModel _viewModel;

		public HealthDetailsProcedurePromptController (IntPtr handle) : base (handle)
		{
			_viewModel = new HealthDetailsProcedurePromptViewModel();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			var controller = GenericPromptDetailController.Create<Procedure> (_viewModel, this);
			var image = UIImage.FromFile ("procedures.png");

			controller.Image = image;
		}

		public override async void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			await _viewModel.WillAppear ();
		}

		public override void OnRequestLookupPage (object sender, EventArgs args)
		{
			var storyboard = UIStoryboard.FromName ("MainStoryboard", null);
			var controller = storyboard.InstantiateViewController ("ProcedureLookupListController") as ProcedureLookupListController;
			var navController = new UINavigationController (controller);

			navController.ConfigureToCompassDefaults (false);

			this.PresentViewController (navController, true, null);
		}

		public override void OnRequestNextPage (object sender, object model)
		{
			var controller = new HealthDetailsProcedureTableController ();

			NavigationController.PushViewController (controller, false);
		}
	}
}
