// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.VM;

namespace iOS.Phone
{
	public partial class HealthDetailsResultPromptController : BasePromptController
	{
		private HealthDetailsResultPromptViewModel _viewModel;

		public HealthDetailsResultPromptController (IntPtr handle) : base (handle)
		{
			_viewModel = new HealthDetailsResultPromptViewModel ();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			var controller = GenericPromptDetailController.Create<BiometricResult> (_viewModel, this);
			var image = UIImage.FromFile ("heart.png");

			controller.Image = image;
		}

		public override async void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			await _viewModel.WillAppear ();
		}

		public override void OnRequestLookupPage (object sender, EventArgs args)
		{
			//TODO: schedule a screening -- future sprint
		}

		public override void OnRequestNextPage (object sender, object model)
		{
			var controller = new HealthDetailsResultTableController ();

			NavigationController.PushViewController (controller, false);
		}

	}
}
