// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class HealthDetailsProcedureNavigationController : BaseNavigationController
	{
		public HealthDetailsProcedureNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
