// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;

namespace iOS.Phone
{
	public partial class HealthDetailsConditionPromptController : BasePromptController
	{
		private HealthDetailsConditionPromptViewModel _viewModel;

		public HealthDetailsConditionPromptController (IntPtr handle) : base (handle)
		{
			_viewModel = new HealthDetailsConditionPromptViewModel ();
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			var controller = GenericPromptDetailController.Create<Condition> (_viewModel, this);
			var image = UIImage.FromFile ("Conditions.png");

			controller.Image = image;
		}

		public override async void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			await _viewModel.WillAppear ();
		}

		public override void OnRequestLookupPage (object sender, EventArgs args)
		{
			var controller = new HealthDetailsConditionLookupController ();
			var navController = new UINavigationController (controller);

			navController.ConfigureToCompassDefaults (false);

			this.PresentViewController (navController, true, null);
		}

		public override void OnRequestNextPage (object sender, object model)
		{
			var controller = new HealthDetailsConditionTableController ();

			NavigationController.PushViewController (controller, false);
		}
	}
}
