// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;
using Microsoft.Practices.Unity;
using GalaSoft.MvvmLight.Helpers;
using Shared.BL;
using System.Linq;

namespace iOS.Phone
{
	public partial class DependentPromptController : UIViewController
	{
		private IDependentPromptViewModel _viewModel;
		public DependentPromptController (IntPtr handle) : base (handle)
		{
			_viewModel = IocContainer.GetContainer().Resolve<IDependentPromptViewModel> ();
			Application.VMStore.DependentPromptVM = _viewModel;
		}
		public override async void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			bool shouldAppear = await Application.VMStore.DependentPromptVM.ViewShouldAppear ();

			if (!shouldAppear) {
				var storyboard = UIStoryboard.FromName ("MainStoryboard", null);
				var controller = storyboard.InstantiateViewController ("DependentListController") as DependentListController;

				NavigationController.PushViewController (controller, false);
			}
			NavigationController.SetNavigationBarHidden (true, true);
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			InitBindings ();

			Title = " ";
		}

		private void InitBindings ()
		{
			YesButton.SetCommand ("TouchUpInside", Application.VMStore.DependentPromptVM.DependentInformationCommand);

			NoButton.SetCommand ("TouchUpInside", Application.VMStore.DependentPromptVM.NotRightNowCommand);

			SkipButton.SetCommand ("TouchUpInside", Application.VMStore.DependentPromptVM.SkipCommand);

			ProgressView.Progress = Application.VMStore.DependentPromptVM.Progress;
		}
	}
}
