// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;
using Microsoft.Practices.Unity;

namespace iOS.Phone
{
	public partial class DependentListController : UIViewController
	{
		private DependentListTableController _tableController;
		private IDependentListViewModel _viewModel;

		public DependentListController (IntPtr handle) : base (handle)
		{
			_viewModel = IocContainer.GetContainer().Resolve<IDependentListViewModel> ();
			Application.VMStore.DependentListVM = _viewModel;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_tableController = ChildViewControllers [0] as DependentListTableController;
			_tableController.TableView.Scrolled += HandleScrolled;
		}
			
		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			NavigationController.SetNavigationBarHidden (true, true);

			ProgressView.Progress = IocContainer.GetContainer ().Resolve<IDependentPromptViewModel> ().Progress;
		}

		private void HandleScrolled (object sender, EventArgs e)
		{
			_tableController.TableView.AddParrallax (HeaderView);
		}
	}
}
