// This file has been autogenerated from a class added in the UI designer.
using System;
using Foundation;
using UIKit;
using CoreGraphics;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Shared.Common;
using GalaSoft.MvvmLight.Helpers;
using System.Threading.Tasks;
using Shared.VM;
using Microsoft.Practices.Unity;

namespace iOS.Phone
{
	public partial class DependentInformationController : UIViewController
	{
		private IDependentInformationViewModel _viewModel;
		private DependentInformationTableController _tableController;

		public Dependent SelectedDependent 
		{ 
			get{
				return Application.VMStore.DependentInformationVM.SelectedDependent;
			}
			set
			{
				Application.VMStore.DependentInformationVM.SelectedDependent = value;
			} 
		}
		public bool EditMode 
		{ 
			get { return Application.VMStore.DependentInformationVM.EditMode; }
			set { Application.VMStore.DependentInformationVM.EditMode = value; }
		}

		public DependentInformationController (IntPtr handle) : base (handle)
		{
			_viewModel = IocContainer.GetContainer ().Resolve<IDependentInformationViewModel>();
			Application.VMStore.DependentInformationVM = _viewModel;
		}
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			InitBindings ();

			Title = !EditMode ? ApplicationResources.AddAFamilyMember : ApplicationResources.EditAFamilyMember;

			_tableController = ChildViewControllers [0] as DependentInformationTableController;
			_tableController.TableView.Scrolled += HandleScrolled;
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			if(NavigationController != null && NavigationController.NavigationController != null){
				NavigationController.SetNavigationBarHidden (false, true);
				NavigationController.NavigationBar.BarStyle = UIBarStyle.Black;
			}
		}

		void HandleScrolled (object sender, EventArgs args)
		{
			_tableController.TableView.AddParrallax (_headerView);
		}

		private void InitBindings()
		{
		}
	}
}
