// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Shared.VM;

namespace iOS.Phone
{
	public partial class DoctorLookupListTableController : ExtendedObservableTableViewController<Provider>
	{
		public DoctorLookupListTableController (IntPtr handle) : base (handle) {}

		public override void ConfigureDelegates ()
		{
			this.TableView.RowHeight = 76;

			this.DataSource = Application.VMStore.DoctorLookupVM.Results;

			this.CreateCellDelegate = (id, tableView, indexPath)  =>
			{
				var cell = tableView.DequeueReusableCell(DoctorLookupCell.Key);

				if(tableView.IsScrolledToBottom())
				{
					var parent = ParentViewController as DoctorLookupListController;
					StartAnimating ();

					Application.VMStore.DoctorLookupVM.ShowMoreCommand.Execute (parent.SearchBar.Text);
				}

				return cell;
			};

			this.BindCellDelegate = (cell, provider, indexPath) =>
			{
				var docCell = cell as DoctorLookupCell;

				docCell.Name = provider.DoctorName;
				docCell.Address = provider.SingleLineAddress;
				docCell.Specialty = provider.SpecialtiesDescription;
			};

			this.SelectionChanged += (object sender, EventArgs e) => {
				Application.VMStore.DoctorLookupVM.SelectedResult = this.SelectedItem;
				Application.VMStore.DoctorLookupVM.SelectionCommand.Execute(this.SelectedItem);
			};
		}

		public void StartAnimating ()
		{
			ActivityIndicator.StartAnimating ();
		}

		public void StopAnimating ()
		{
			ActivityIndicator.StopAnimating ();
		}
	}
}
