// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Microsoft.Practices.Unity;
using Shared.VM;

namespace iOS.Phone
{
	public partial class PrescriptionLookupListController : BaseLookupController<Prescription>
	{
		PrescriptionLookupListTableController _tableController;

		public PrescriptionLookupListController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_tableController = ChildViewControllers [0] as PrescriptionLookupListTableController;
			_tableController.StopAnimating ();

			SearchBar.TextChanged += (object sender, UISearchBarTextChangedEventArgs e) => 
			{
				if (!string.IsNullOrWhiteSpace(e.SearchText))
				{
					_tableController.StartAnimating();
					_tableController.View.Hidden = false;
				}
			};
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			if (NavigationController != null) 
			{
				NavigationController.SetNavigationBarHidden (false, true);
			}
		}

		public override void InitViewModel ()
		{
			ViewModel = IocContainer.GetContainer ().Resolve<IPrescriptionLookupViewModel> ();
			Application.VMStore.PrescriptionLookupVM = (IPrescriptionLookupViewModel)ViewModel;

			Application.VMStore.PrescriptionLookupVM.SearchFinished += OnSearchFinished;
		}

		private void OnSearchFinished (object sender, SearchEventArgs args)
		{
			InvokeOnMainThread (() => 
				{
					if (Application.VMStore.PrescriptionLookupVM.Results.Count > 0 || args.SearchCancelled) 
					{
						_tableController.StopAnimating ();
					} 
					else
					{
						_tableController.View.Hidden = true;
						ResultErrorLabel.Text = String.Format("{0} {1}", Application.VMStore.PrescriptionLookupVM.ErrorMessage, SearchBar.Text);
						ResultErrorDetailLabel.Text = Application.VMStore.PrescriptionLookupVM.ErrorDetailMessage;
					}
				}
			);
		}
	}
}
