// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using Shared.Common;
using Microsoft.Practices.Unity;

namespace iOS.Phone
{
	public partial class PrescriptionPromptListController : UIViewController
	{
		private PrescriptionPromptListTableController _tableController;
		private IPrescriptionPromptListViewModel _viewModel;

		public PrescriptionPromptListController (IntPtr handle) : base (handle)
		{
			_viewModel = IocContainer.GetContainer().Resolve<IPrescriptionPromptListViewModel> ();
			Application.VMStore.PrescriptionPromptListVM = _viewModel;

		}
			
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_tableController = ChildViewControllers [0] as PrescriptionPromptListTableController;
			_tableController.TableView.Scrolled += HandleScrolled;
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			NavigationController.SetNavigationBarHidden (true, true);

			ProgressView.Progress = IocContainer.GetContainer ().Resolve<IPrescriptionPromptViewModel> ().Progress;
		}

		private void HandleScrolled (object sender, EventArgs args)
		{
			_tableController.TableView.AddParrallax (HeaderView);
		}
	}
}
