// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;

namespace iOS.Phone
{
	public partial class PrescriptionLookupListTableController : ExtendedObservableTableViewController<Prescription>
	{
		public PrescriptionLookupListTableController (IntPtr handle) : base (handle)
		{
		}

		public override void ConfigureDelegates ()
		{
			this.TableView.RowHeight = 56;

			this.DataSource = Application.VMStore.PrescriptionLookupVM.Results;

			this.CreateCellDelegate = (id, tableView, indexPath)  =>
			{
				var cell = tableView.DequeueReusableCell(PrescriptionLookupCell.Key);

				if(tableView.IsScrolledToBottom())
				{
					StartAnimating ();
					var parent = ParentViewController as PrescriptionLookupListController;
					Application.VMStore.PrescriptionLookupVM.ShowMoreCommand.Execute (parent.SearchBar.Text);
				}
				return cell;
			};

			this.BindCellDelegate = (cell, prescription, indexPath) =>
			{
				var preCell = cell as PrescriptionLookupCell;

				preCell.ContentText = prescription.Name;
			};

			this.SelectionChanged += (object sender, EventArgs e) => {
				Application.VMStore.PrescriptionLookupVM.SelectedResult = this.SelectedItem;
				Application.VMStore.PrescriptionLookupVM.SelectionCommand.Execute(this.SelectedItem);
			};

		}

		public void StartAnimating ()
		{
			ActivityIndicator.StartAnimating ();
		}

		public void StopAnimating ()
		{
			ActivityIndicator.StopAnimating ();
		}
	}
}
