// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Microsoft.Practices.Unity;
using Shared.VM;
using iOS;

namespace iOS.Phone
{
	public partial class ProcedurePromptListController : UIViewController
	{
		private ProcedurePromptListTableController _tableController;
		private IProcedurePromptListViewModel _viewModel;

		public ProcedurePromptListController (IntPtr handle) : base (handle)
		{
			_viewModel = IocContainer.GetContainer().Resolve<IProcedurePromptListViewModel> ();
			Application.VMStore.ProcedurePromptListVM = _viewModel;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_tableController = ChildViewControllers [0] as ProcedurePromptListTableController;
			_tableController.TableView.Scrolled += HandleScrolled;

		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			NavigationController.SetNavigationBarHidden (true, true);

			ProgressView.Progress = IocContainer.GetContainer ().Resolve<IProcedurePromptViewModel> ().Progress;
		}

		private void HandleScrolled (object sender, EventArgs args)
		{
			_tableController.TableView.AddParrallax (HeaderView);
		}
	}
}
