// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;

namespace iOS.Phone
{
	public partial class 
	ProcedureLookupListTableController : ExtendedObservableTableViewController<Procedure>
	{
		public ProcedureLookupListTableController (IntPtr handle) : base (handle) { }

		public override void ConfigureDelegates ()
		{
			this.TableView.RowHeight = 62;

			this.DataSource = Application.VMStore.ProcedureLookupVM.Results;

			this.CreateCellDelegate = (id, tableView, indexPath)  =>
			{
				var cell = tableView.DequeueReusableCell(ProcedureLookupCell.Key);

				if(tableView.IsScrolledToBottom())
				{
					StartAnimating ();
					var parent = ParentViewController as ProcedureLookupListController;
					Application.VMStore.ProcedureLookupVM.ShowMoreCommand.Execute (parent.SearchBar.Text);
				}
				return cell;
			};

			this.BindCellDelegate = (cell, procedure, indexPath) =>
			{
				var preCell = cell as ProcedureLookupCell;

				preCell.ContentText = procedure.Description;
			};

			this.SelectionChanged += (object sender, EventArgs e) => {
				var parent = ParentViewController as ProcedureLookupListController;
				parent.SearchBar.ResignFirstResponder();

				Application.VMStore.ProcedureLookupVM.SelectedResult = this.SelectedItem;
				Application.VMStore.ProcedureLookupVM.SelectionCommand.Execute(this.SelectedItem);
			};
		}

		public void StartAnimating ()
		{
			ActivityIndicator.StartAnimating ();
		}

		public void StopAnimating ()
		{
			ActivityIndicator.StopAnimating ();
		}
	}
}
