// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;
using Microsoft.Practices.Unity;
using Shared.VM;

namespace iOS.Phone
{
	public partial class ProcedureLookupListController : BaseLookupController<Procedure>
	{
		ProcedureLookupListTableController _tableController;

		public ProcedureLookupListController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			_tableController = ChildViewControllers [0] as ProcedureLookupListTableController;
			_tableController.StopAnimating ();

			SearchBar.TextChanged += (object sender, UISearchBarTextChangedEventArgs e) => 
			{
				if (!string.IsNullOrWhiteSpace(e.SearchText))
				{
				_tableController.StartAnimating();
				_tableController.View.Hidden = false;
				}
			};
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			NavigationController.SetNavigationBarHidden (false, true);
		}

		public override void InitViewModel ()
		{
			ViewModel = IocContainer.GetContainer ().Resolve<IProcedureLookupViewModel> ();
			Application.VMStore.ProcedureLookupVM = (IProcedureLookupViewModel)ViewModel;

			Application.VMStore.ProcedureLookupVM.SearchFinished += OnSearchFinished;
		}

		private void OnSearchFinished (object sender, SearchEventArgs args)
		{
			InvokeOnMainThread (() => 
				{
					if (Application.VMStore.ProcedureLookupVM.Results.Count > 0 || args.SearchCancelled) 
					{
						_tableController.StopAnimating ();
					} 
					else
					{
						_tableController.View.Hidden = true;
						ResultErrorLabel.Text = String.Format("{0} {1}", Application.VMStore.ProcedureLookupVM.ErrorMessage, SearchBar.Text);
						ResultErrorDetailLabel.Text = Application.VMStore.ProcedureLookupVM.ErrorDetailMessage;
					}
				}
			);
		}
	}
}
