// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class ProcedureLookupCell : UITableViewCell
	{
		public static readonly string Key = "ProcedureLookupCell";

		public string ContentText { 
			get { return ContentLabel.Text; }
			set { ContentLabel.Text = value; }
		}

		public ProcedureLookupCell (IntPtr handle) : base (handle)
		{
		}
	}
}
