// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using GalaSoft.MvvmLight.Helpers;
using System.ComponentModel;

namespace iOS.Phone
{
	public partial class MenuItemCell : BaseCell
	{
		#region Properties

		public BaseMenuItemViewModel ViewModel { get; set; }

		#endregion

		#region Methods

		public MenuItemCell (IntPtr handle) : base (handle)
		{
		}

		protected override async void ConfigureSubviews (IListItem item)
		{
			ViewModel = item as BaseMenuItemViewModel;

			await ViewModel.DidLoad ();

			InitUI ();
			InitBindings ();
		}

		private void InitUI ()
		{
			UserInteractionEnabled = ViewModel.UserInteractionEnabled;
			TitleLabel.Text = ViewModel.Title;
			SubtitleLabel.Text = ViewModel.Subtitle;
			MainImageView.Image = UIImage.FromFile (ViewModel.ImageName);
		}

		private void InitBindings ()
		{
			ViewModel.PropertyChanged -= OnPropertyChanged;
			ViewModel.PropertyChanged += OnPropertyChanged;
		}

		private void OnPropertyChanged (object sender, PropertyChangedEventArgs e)
		{
			if(e.PropertyName.Equals("ImageName") || e.PropertyName.Equals("MenuItemType")) {
				MainImageView.Image = UIImage.FromFile (ViewModel.ImageName);	
			} 
			else if (e.PropertyName.Equals("Title")) {
				TitleLabel.Text = ViewModel.Title;
			} 
			else if (e.PropertyName.Equals("Subtitle")) {
				SubtitleLabel.Text = ViewModel.Subtitle;
			} 
			else if (e.PropertyName.Equals("UserInteractionEnabled")) {
				UserInteractionEnabled = ViewModel.UserInteractionEnabled;
			}
		}

		#endregion
	}
}
