// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;

namespace iOS.Phone
{
	public partial class MenuItemCell : BaseCell
	{
		public MenuItemCell (IntPtr handle) : base (handle)
		{
		}

		protected override void ConfigureSubviews (IListItem item)
		{
			var viewModel = (BaseMenuItemViewModel)item;

			TitleLabel.Text = viewModel.Title;
			SubtitleLabel.Text = viewModel.Subtitle;
			MainImageView.Image = UIImage.FromFile (viewModel.ImageName);

			viewModel.RequestDefaultFormat = OnRequestDefaultFormat;
			viewModel.RequestLoggedInFormat = OnRequestLoggedInFormat;
			viewModel.RequestLoggedOutFormat = OnRequestLoggedOutFormat;
		}

		private void OnRequestDefaultFormat(BaseMenuItemViewModel viewModel)
		{
			
		}

		private void OnRequestLoggedInFormat(BaseMenuItemViewModel viewModel)
		{

		}

		private void OnRequestLoggedOutFormat(BaseMenuItemViewModel viewModel)
		{

		}
	}
}
