// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class GenericSectionHeader : UITableViewCell
	{
		public static readonly NSString Key = new NSString ("GenericSectionHeader");

		public string Title 
		{
			get { return TitleLabel.Text; }
			set { TitleLabel.Text = value; }
		}

		public GenericSectionHeader (IntPtr handle) : base (handle)
		{
		}
	}
}
