// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class GenericAddCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString ("GenericAddCell");

		public string Title 
		{
			get { return TitleLabel.Text; }
			set { TitleLabel.Text = value; }
		}

		public event EventHandler Action
		{
			add { ActionButton.TouchUpInside += value; }
			remove { ActionButton.TouchUpInside -= value; }
		}
		public GenericAddCell (IntPtr handle) : base (handle)
		{
		}
	}
}
