// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using GalaSoft.MvvmLight.Helpers;

namespace iOS.Phone
{
	public partial class GenericPromptDetailController : GenericPromptController
	{
		public override UIImage Image
		{
			get { return ImageView.Image; }
			set { ImageView.Image = value; }
		}

		protected GenericPromptDetailController (IntPtr handle) : base (handle) { }

		public static new GenericPromptDetailController Create<T> (BasePromptViewModel<T> viewModel, BasePromptController containerController)
		{
			var storyboard = UIStoryboard.FromName ("HealthDetailsStoryboard", null);
			var childController = storyboard.InstantiateViewController ("GenericPromptDetailController") as GenericPromptDetailController;

			// Step 1: Set ViewModel Events
			viewModel.RequestLookupPage += containerController.OnRequestLookupPage;
			viewModel.RequestNextPage += containerController.OnRequestNextPage;
			viewModel.RequestPreviousPage += childController.OnRequestPreviousPage;

			if(viewModel.Title != null)
			{
				containerController.Title = viewModel.Title;
			}

			containerController.View.AddSubview (childController.View);
			containerController.AddChildViewController (childController);

			containerController.View.SetNeedsLayout ();
			containerController.View.LayoutIfNeeded ();

			// Step 3: Setup Child Controller
			childController.PromptButton.SetTitle(viewModel.PromptTitle, UIControlState.Normal);
			childController.ContentHeaderLabel.Text = viewModel.ContentTitle;
			childController.ContentBodyLabel.Text = viewModel.ContentDetail;
			childController.ContentFooterLabel.Text = viewModel.ContentFooter;

			childController.PromptButton.SetCommand ("TouchUpInside", viewModel.LookupCommand);

			return childController;
		} 
	}
}
