// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using iOS;

namespace iOS.Phone
{
	public partial class GenericAttestationTableController : UITableViewController
	{
		public GenericAttestationTableController (IntPtr handle) : base (handle)
		{
		}
	}
}
