// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.Common;

namespace iOS.Phone
{
	public partial class DocFacController : UIViewController
	{
		public DocFacController (IntPtr handle) : base (handle)
		{
			// this will be refactored into a viewmodel once this controller is tabbed for doctors and facilities and needs a viewmodel to handle logic
			Title = ApplicationResources.MyDoctors;
		}
	}
}
