// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using GalaSoft.MvvmLight.Helpers;
using Shared.VM;
using Shared.Common;
using Microsoft.Practices.Unity;
using TelerikUI;

namespace iOS.Phone
{
	public partial class CalendarController : UIViewController
	{
		private ICalendarViewModel _viewModel;
		private TKCalendarSelectionMode _selectionMode = TKCalendarSelectionMode.Single;

		public CalendarParameters Parameters { get; set;}

		public CalendarController (IntPtr handle) : base (handle)
		{
			_viewModel = IocContainer.GetContainer ().Resolve<ICalendarViewModel> ();

			Application.VMStore.CalendarVM = _viewModel;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			InitBindings ();

			CalendarView.MaxDate = Parameters.MaxDate.ToNSDate();
			CalendarView.MinDate = Parameters.MinDate.ToNSDate ();
			CalendarView.SelectedDate = Parameters.SelectedDate.ToNSDate ();
			CalendarView.SelectionMode = Parameters.SelectionMode.ToTKCalenderSelectionMode ();
			CalendarView.Delegate = new CalendarDelegate (_viewModel);
			Title = ApplicationResources.CalendarTitle;
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			if(NavigationController != null)
			{
				NavigationController.SetNavigationBarHidden (false, true);
				NavigationController.NavigationBar.BarTintColor = SharedColors.CompassBlue.ToUIColor ();
				NavigationController.NavigationBar.TintColor = SharedColors.White.ToUIColor ();
				NavigationController.NavigationBar.TitleTextAttributes = new UIStringAttributes {
					ForegroundColor = UIColor.White,
					Font = UIFont.FromName("FuturaStd-Bold", 16f)
				};
			}
		}

		private void InitBindings ()
		{
			Application.VMStore.CalendarVM.Parameters = Parameters;

			AddButton.SetCommand ("TouchUpInside", Application.VMStore.CalendarVM.AddCommand);
		}
	}

	public class CalendarDelegate : TKCalendarDelegate
	{
		private ICalendarViewModel _viewModel;

		public CalendarDelegate (ICalendarViewModel viewModel)
		{
			_viewModel = viewModel;
		}

		public override void DidSelectDate (TKCalendar calendar, NSDate date)
		{
			_viewModel.Parameters.OnDateSelected (date.ToDateTime ());
			_viewModel.Parameters.SelectedDate = date.ToDateTime ();
		}
	}
}
