// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Shared.VM;
using GalaSoft.MvvmLight.Helpers;

namespace iOS.Phone
{
	public partial class MenuController : UIViewController
	{
		#region Variables

		private PSObservableTableController _tableController;

		#endregion

		#region Properties

		public MenuViewModel ViewModel { get; set; }

		#endregion

		#region Methods

		public MenuController (IntPtr handle) : base (handle)
		{
			if(ViewModel == null) {
				ViewModel = new MenuViewModel ();
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SubtitleLabel.Alpha = ViewModel.ItemViewModels.Count == 0 ? 1 : 0;
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			if(segue.DestinationViewController.GetType() == typeof(PSObservableTableController)) {

				_tableController = segue.DestinationViewController as PSObservableTableController;

				_tableController.Collection = ViewModel.ItemViewModels;
				_tableController.SetEstimatedHeight (40);

				_tableController.View.Alpha = ViewModel.ItemViewModels.Count == 0 ? 0 : 1;
			}
		}

		#endregion
	}
}
