// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iOS.Phone
{
	public partial class OnboardingController : UIViewController
	{
		#region Methods

		public OnboardingController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			InitUI ();
		}

		private void InitUI ()
		{
			// Setup UI elements
			InitSocialButton(FacebookButton);
			InitSocialButton (TwitterButton);

			GoButton.Layer.CornerRadius = 4;
			GoButton.Layer.BorderColor = GoButton.TitleLabel.TextColor.CGColor;
			GoButton.Layer.BorderWidth = 1;

			// Animations
			View.SetNeedsLayout ();

			TitleLabelCenterYConstraint.Constant = 120;
			GoButton.Enabled = false;
			FacebookButton.Alpha = 0;
			TwitterButton.Alpha = 0;
			GoButton.Alpha = 0;
			SubtitleLabel.Alpha = 0;

			UIView.Animate (0.75, () => {
				TitleLabel.LayoutIfNeeded();
			}, () => {
				UIView.Animate(0.5, () => {
					FacebookButton.Alpha = 1;			
				}, () => {
					UIView.Animate(0.5, () => {
						TwitterButton.Alpha = 1;	
					}, () => {
						UIView.Animate(0.5, () => {
							GoButtonBottomConstraint.Constant = 35;
							GoButton.Alpha = 1;	
						});
					});
				});
			});
		}

		private void InitBindings ()
		{
			
		}

		private void InitSocialButton (UIButton button)
		{
			button.Layer.CornerRadius = button.Frame.Height / 2;
			button.Layer.BorderWidth = 1;
			button.Layer.BorderColor = button.TitleLabel.TextColor.CGColor;
			button.TitleLabel.BackgroundColor = UIColor.Clear;
			button.TouchUpInside += OnSocialButtonTouchUpInside;
		}

		private void OnSocialButtonTouchUpInside (object sender, EventArgs args)
		{
			var button = sender as UIButton;

			button.Selected = !button.Selected;

			if(button.Selected) {
				button.BackgroundColor = UIColor.FromCGColor (button.Layer.BorderColor);
				button.TitleLabel.TextColor = UIColor.White;	
			} else {
				button.BackgroundColor = UIColor.Clear;
				button.TitleLabel.TextColor = UIColor.FromCGColor (button.Layer.BorderColor);	
			}
			button.TitleLabel.BackgroundColor = UIColor.Clear;
		}

		#endregion
	}
}
